In [5]:
pip install basketball-reference-scraper

Requirement already satisfied: basketball-reference-scraper in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (1.0.26)
Requirement already satisfied: python-dateutil==2.8.1 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (2.8.1)
Requirement already satisfied: six==1.13.0 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (1.13.0)
Requirement already satisfied: numpy==1.18.1 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (1.18.1)
Requirement already satisfied: pandas==0.25.3 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (0.25.3)
Requirement already satisfied: bs4==0.0.1 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (0.0.1)
Requirement already satisfied: requests==2.22.0 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (2.22.0)
Requirement already satisfied: pytz==2019.3 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (2019.3)
Requirement already satisfied: beautifulsoup4==4.8.2 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (4.8.2)
Requirement already satisfied: lxml==4.4.2 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (4.4.2)
Requirement already satisfied: soupsieve==1.9.5 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (1.9.5)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (1.25.9)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (2020.6.20)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (2.8)
Note: you may need to restart the kernel to use updated packages.

In [1]:
from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats, get_team_misc

In [8]:
s = get_team_stats('GSW', 2019, data_format='PER_GAME')
print(s)

G              82
MP          241.5
FG             44
FGA          89.8
FG%         0.491
3P           13.3
3PA          34.4
3P%         0.385
2P           30.8
2PA          55.3
2P%         0.557
FT           16.3
FTA          20.4
FT%         0.801
ORB           9.7
DRB          36.5
TRB          46.2
AST          29.4
STL           7.6
BLK           6.4
TOV          14.3
PF           21.4
PTS         117.7
TEAM          GSW
SEASON    2018-19
dtype: object

In [6]:
s = get_opp_stats('GSW', 2019, data_format='PER_GAME')
print(s)

OPP_G           82
OPP_MP       241.5
OPP_FG        40.4
OPP_FGA       91.1
OPP_FG%      0.444
OPP_3P        11.6
OPP_3PA       33.6
OPP_3P%      0.347
OPP_2P        28.8
OPP_2PA       57.5
OPP_2P%        0.5
OPP_FT        18.7
OPP_FTA       24.2
OPP_FT%      0.773
OPP_ORB       10.8
OPP_DRB       33.5
OPP_TRB       44.3
OPP_AST       24.3
OPP_STL        7.7
OPP_BLK        3.6
OPP_TOV       13.5
OPP_PF        19.5
OPP_PTS      111.2
TEAM           GSW
SEASON     2018-19
dtype: object

In [2]:
from basketball_reference_scraper.box_scores import get_box_scores

s = get_box_scores('2020-01-13', 'CHI', 'BOS', period='GAME', stat_type='BASIC')
print(s)

{'CHI':                 PLAYER     MP  FG FGA    FG% 3P 3PA    3P%  FT FTA  ... ORB  \
0          Zach LaVine  34:52   9  18   .500  3   6   .500   9   9  ...   1
1            Kris Dunn  30:01   3   7   .429  1   2   .500   2   3  ...   0
2     Tomáš Satoranský  25:55   3   8   .375  0   1   .000   6   8  ...   1
3      Lauri Markkanen  25:20   4   9   .444  0   3   .000   1   2  ...   1
4       Daniel Gafford  20:24   4   5   .800  0   0    NaN   2   2  ...   2
5       Thaddeus Young  24:23   8  14   .571  1   4   .250   0   0  ...   0
6           Coby White  23:23   3   8   .375  0   4   .000   0   0  ...   1
7          Luke Kornet  21:53   0   2   .000  0   2   .000   0   0  ...   0
8   Chandler Hutchison  14:24   1   5   .200  0   0    NaN   0   0  ...   1
9     Ryan Arcidiacono  13:25   0   2   .000  0   2   .000   0   0  ...   0
10    Denzel Valentine   2:00   2   2  1.000  1   1  1.000   0   0  ...   0
11  Shaquille Harrison   2:00   0   1   .000  0   0    NaN   1   2  ...   0
12   Cristiano Felício   2:00   0   0    NaN  0   0    NaN   0   0  ...   0
13         Team Totals    240  37  81   .457  6  25   .240  21  26  ...   7

   DRB TRB AST STL BLK TOV  PF  PTS  +/-
0    4   5   2   1   0   6   3   30   -7
1    5   5   1   0   0   2   2    9   -5
2    0   1   7   1   0   2   2   12   +3
3    5   6   0   2   0   0   3    9   -5
4    1   3   1   0   2   0   4   10   +8
5    2   2   1   0   0   1   1   17  -11
6    2   3   4   0   0   1   1    6  -18
7    5   5   0   0   1   1   2    0  -24
8    2   3   0   1   2   1   2    2   -6
9    3   3   0   0   0   0   2    0   -7
10   1   1   0   0   0   0   0    5   +4
11   1   1   0   0   0   0   0    1   +4
12   0   0   0   0   0   0   0    0   +4
13  31  38  16   5   5  14  22  101  NaN

[14 rows x 21 columns], 'BOS':              PLAYER     MP  FG FGA   FG% 3P 3PA    3P%  FT FTA  ... ORB DRB  \
0      Jaylen Brown  30:15   5  13  .385  0   1   .000   9   9  ...   2   1
1    Gordon Hayward  30:09   4  11  .364  0   1   .000   0   0  ...   0   6
2      Jayson Tatum  29:43   7  17  .412  2   7   .286   5   7  ...   0   6
3      Kemba Walker  27:36   5   9  .556  3   6   .500   1   2  ...   0   4
4       Enes Kanter  26:27   7   9  .778  0   0    NaN   1   1  ...   2   7
5      Marcus Smart  33:24   4   8  .500  2   5   .400   2   2  ...   0   5
6    Brad Wanamaker  24:11   3   5  .600  1   1  1.000   2   2  ...   1   2
7    Grant Williams  16:17   4   8  .500  1   2   .500   2   2  ...   4   1
8      Semi Ojeleye  12:57   0   0   NaN  0   0    NaN   0   0  ...   1   0
9   Vincent Poirier   5:01   0   3  .000  0   0    NaN   2   2  ...   0   0
10   Romeo Langford   2:00   0   0   NaN  0   0    NaN   2   2  ...   0   0
11    Javonte Green   2:00   0   0   NaN  0   0    NaN   0   0  ...   0   1
12      Team Totals    240  39  83  .470  9  23   .391  26  29  ...  10  33

   TRB AST STL BLK TOV  PF  PTS  +/-
0    3   3   2   0   0   3   19  +10
1    6   8   0   0   1   3    8  +14
2    6   2   1   2   1   1   21   -2
3    4   2   0   2   2   1   14   +2
4    9   0   1   1   5   3   15   +4
5    5   8   3   0   1   3   12  +25
6    3   2   0   0   0   1    9   +7
7    5   3   0   1   1   2   11  +11
8    1   0   0   0   0   0    0    0
9    0   0   0   0   1   2    2   -3
10   0   0   0   0   0   0    2   -4
11   1   0   0   0   0   0    0   -4
12  43  28   7   6  12  19  113  NaN

[13 rows x 21 columns]}

In [3]:
from basketball_reference_scraper.seasons import get_schedule, get_standings

s = get_schedule(2020, playoffs=False)
print(s)

           DATE                VISITOR  VISITOR_PTS                    HOME  \
0    2019-10-22   New Orleans Pelicans          122         Toronto Raptors
1    2019-10-22     Los Angeles Lakers          102    Los Angeles Clippers
2    2019-10-23         Denver Nuggets          108  Portland Trail Blazers
3    2019-10-23       Sacramento Kings           95            Phoenix Suns
4    2019-10-23  Oklahoma City Thunder           95               Utah Jazz
...         ...                    ...          ...                     ...
1055 2020-08-14         Denver Nuggets          109         Toronto Raptors
1056 2020-08-14             Miami Heat           92          Indiana Pacers
1057 2020-08-14  Oklahoma City Thunder          103    Los Angeles Clippers
1058 2020-08-14     Philadelphia 76ers          134         Houston Rockets
1059 2020-08-15      Memphis Grizzlies          122  Portland Trail Blazers

      HOME_PTS
0          130
1          112
2          100
3          124
4          100
...        ...
1055       117
1056       109
1057       107
1058        96
1059       126

[1060 rows x 5 columns]

In [4]:
from basketball_reference_scraper.shot_charts import get_shot_chart

s = get_shot_chart('2020-01-13', 'CHI', 'BOS')
print(s)

{'CHI':           x        y  QUARTER TIME_REMAINING              PLAYER MAKE_MISS  \
0   13.8 ft  26.7 ft        1        11:17.0     Lauri Markkanen      MISS
1   31.7 ft  17.6 ft        1        10:37.0    Tomáš Satoranský      MISS
2   32.0 ft  8.26 ft        1        10:06.0     Lauri Markkanen      MISS
3   24.0 ft  2.68 ft        1        10:05.0     Lauri Markkanen      MAKE
4   24.5 ft  4.97 ft        1         9:13.0      Daniel Gafford      MAKE
..      ...      ...      ...            ...                 ...       ...
76  25.3 ft  3.58 ft        4         3:35.0         Zach LaVine      MAKE
77  8.20 ft  27.8 ft        4         2:54.0         Zach LaVine      MAKE
78  17.7 ft  11.2 ft        4         1:47.0  Shaquille Harrison      MISS
79  17.2 ft  16.4 ft        4         0:54.0    Denzel Valentine      MAKE
80   6.1 ft  20.7 ft        4         0:18.0    Denzel Valentine      MAKE

    VALUE DISTANCE
0       3    26 ft
1       2    16 ft
2       2     9 ft
3       2     1 ft
4       2     2 ft
..    ...      ...
76      2     1 ft
77      3    29 ft
78      2    10 ft
79      2    15 ft
80      3    25 ft

[81 rows x 8 columns], 'BOS':           x        y  QUARTER TIME_REMAINING           PLAYER MAKE_MISS  \
0   25.9 ft  3.78 ft        1        11:35.0      Enes Kanter      MAKE
1    9.6 ft  9.55 ft        1        11:00.0     Jayson Tatum      MAKE
2   24.3 ft  4.77 ft        1         8:50.0      Enes Kanter      MAKE
3   22.5 ft  3.28 ft        1         8:19.0      Enes Kanter      MAKE
4   19.9 ft  8.16 ft        1         7:39.0     Jayson Tatum      MISS
..      ...      ...      ...            ...              ...       ...
78  25.3 ft  5.17 ft        4         3:03.0   Gordon Hayward      MAKE
79   6.7 ft  21.7 ft        4         2:39.0     Kemba Walker      MAKE
80  24.9 ft  29.1 ft        4         2:02.0     Kemba Walker      MAKE
81  34.1 ft  17.1 ft        4         1:33.0  Vincent Poirier      MISS
82  19.9 ft  5.17 ft        4         0:33.0  Vincent Poirier      MISS

    VALUE DISTANCE
0       2     2 ft
1       2    16 ft
2       2     2 ft
3       2     2 ft
4       2     6 ft
..    ...      ...
78      2     2 ft
79      3    25 ft
80      3    26 ft
81      2    17 ft
82      2     5 ft

[83 rows x 8 columns]}

In [5]:
from basketball_reference_scraper.injury_report import get_injury_report

s = get_injury_report()
print(s)

                PLAYER TEAM       DATE  \
0   Bogdan BogdanoviÄ‡  ATL 2021-01-12
1            Kris Dunn  ATL 2021-01-28
2      De'Andre Hunter  ATL 2021-02-02
3       Onyeka Okongwu  ATL 2021-02-03
4       Romeo Langford  BOS 2020-12-01
..                 ...  ...        ...
87       Patrick McCaw  TOR 2020-12-16
88       Elijah Hughes  UTA 2021-02-03
89       Thomas Bryant  WAS 2021-01-10
90           Raul Neto  WAS 2021-02-01
91   Russell Westbrook  WAS 2021-02-03

                                          DESCRIPTION          STATUS  \
0   General ManagerÃ‚ Travis Schlenk said Bogdanov...             Out
1   The Hawks announced that Dunn will miss at lea...             Out
2   Hunter is listed as OUT for Wednesday's (Feb. ...             Out
3   The Hawks have listed Okongwu as OUT for Wedne...             Out
4   The Celtics announced G-F Romeo Langford under...             Out
..                                                ...             ...
87  Raptors coach Nick Nurse said there's no timet...             Out
88  The Jazz have listed Hughes as OUT for Thursda...             Out
89  Bryant tore the ACL in his left knee, accordin...  Out For Season
90  Wizards coach Scott Brooks said Neto is expect...             Out
91  Westbrook is out for Wednesday's (Feb. 3) game...             Out

         INJURY
0          Knee
1   Right ankle
2    Right knee
3      Achilles
4   Right wrist
..          ...
87         Knee
88        Ankle
89    Left knee
90        Groin
91         Rest

[92 rows x 6 columns]

In [6]:
from basketball_reference_scraper.players import get_game_logs, get_player_headshot

df = get_game_logs('Pau Gasol', '2010-01-12', '2010-01-20', playoffs=False)
print(df)

url = get_player_headshot('Kobe Bryant')
print(url)

You searched for "Pau Gasol"
7 results found.
0: Pau Gasol
1: Marc Gasol
2: Paul Watson
3: Paul Davis
4: Paul Grant
5: Paul Long
6: Paul Silas
Pick one: 0
Results for Pau Gasol:

         DATE     AGE TEAM HOME/AWAY OPPONENT   RESULT GS     MP FG FGA  ...  \
40 2010-01-15  29-193  LAL      HOME      LAC  W (+40)  1  30:29  4  10  ...
42 2010-01-18  29-196  LAL      HOME      ORL   W (+6)  1  39:32  8  14  ...

   DRB TRB AST STL BLK TOV PF PTS GAME_SCORE  +/-
40   2   6   3   0   3   1  0  20       21.2  +22
42   7  10   2   1   0   1  4  17       14.4   +7

[2 rows x 28 columns]
You searched for "Kobe Bryant"
4 results found.
0: Kobe Bryant
1: Joe Bryant
2: Em Bryant
3: Mark Bryant
Pick one: 0
Results for Kobe Bryant:

https://d2cwpp38twqe55.cloudfront.net/req/202006192/images/players/bryanko01.jpg

In [7]:
team_to_abbreviation = {
    "ATLANTA HAWKS" : "ATL",
    "ST. LOUIS HAWKS" : "SLH",
    "MILWAUKEE HAWKS" : "MIL",
    "TRI-CITIES BLACKHAWKS" : "TCB",
    "BOSTON CELTICS" : "BOS",
    "BROOKLYN NETS" : "BRK",
    "NEW JERSEY NETS" : "NJN",
    "CHICAGO BULLS" : "CHI",
    "CHARLOTTE HORNETS": "CHH",
    "CHARLOTTE HORNETS": "CHO",
    "CHARLOTTE BOBCATS" : "CHA",
    "CLEVELAND CAVALIERS": "CLE",
    "DALLAS MAVERICKS" : "DAL",
    "DENVER NUGGETS" : "DEN",
    "DETROIT PISTONS" : "DET",
    "FORT WAYNE PISTONS" : "FWP",
    "GOLDEN STATE WARRIORS" : "GSW",
    "SAN FRANCISCO WARRIORS" : "SFW",
    "PHILADELPHIA WARRIORS" : "PHI",
    "HOUSTON ROCKETS" : "HOU",
    "INDIANA PACERS" : "IND",
    "LOS ANGELES CLIPPERS" : "LAC",
    "SAN DIEGO CLIPPERS" : "SDC",
    "BUFFALO BRAVES" : "BUF",
    "LOS ANGELES LAKERS" : "LAL",
    "MINNEAPOLIS LAKERS" : "MIN",
    "MEMPHIS GRIZZLIES" : "MEM",
    "VANCOUVER GRIZZLIES" : 'VAN',
    "MIAMI HEAT" : "MIA",
    "MILWAUKEE BUCKS" : "MIL",
    "MINNESOTA TIMBERWOLVES" : "MIN",
    "NEW ORLEANS PELICANS" : "NOP",
    "NEW ORLEANS HORNETS" : "NOK",
    "NEW ORLEANS HORNETS" : "NOH",
    "NEW YORK KNICKS" : "NYK",
    "OKLAHOMA CITY HORNETS" : "NOK",
    "OKLAHOMA CITY THUNDER" : "OKC",
    "SEATTLE SUPERSONICS" : "SEA",
    "ORLANDO MAGIC" : "ORL",
    "PHILADELPHIA 76ERS" : "PHI",
    "SYRACUSE NATIONALS" : "SYR",
    "PHOENIX SUNS" : "PHO",
    "PORTLAND TRAIL BLAZERS" : "POR",
    "SACRAMENTO KINGS" : "SAC",
    "KANSAS CITY KINGS" : "KCK",
    "KANSAS CITY-OMAHA KINGS" : "KCK",
    "CINCINNATI ROYALS" : "CIN",
    "ROCHESTER ROYALS" : "ROR",
    "SAN ANTONIO SPURS" : "SAS",
    "TORONTO RAPTORS" : "TOR",
    "UTAH JAZZ" : "UTA",
    "NEW ORLEANS JAZZ" : "NOJ",
    "WASHINGTON WIZARDS" : "WAS",
    "WASHINGTON BULLETS" : "WAS",
    "CAPITAL BULLETS" : "CAP",
    "BALTIMORE BULLETS" : "BAL",
    "CHICAGO ZEPHYRS" : "CHI",
    "CHICAGO PACKERS" : "CHI",
    "ANDERSON PACKERS" : "AND",
    "CHICAGO STAGS" : "CHI",
    "INDIANAPOLIS OLYMPIANS" : "IND",
    "SHEBOYGAN RED SKINS" : "SRS",
    "ST. LOUIS BOMBERS" : "SLB",
    "WASHINGTON CAPITOLS" : "WAS",
    "WATERLOO HAWKS" : "WAT"
}

In [8]:
# get a team's past 10 games from a given date:

#let's look at Golden State's 73-9 record from the 2015-2016 season
season_2016_df = get_schedule(2016, playoffs=False)

season_2016_df

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS
0,2015-10-27,Cleveland Cavaliers,95,Chicago Bulls,97
1,2015-10-27,Detroit Pistons,106,Atlanta Hawks,94
2,2015-10-27,New Orleans Pelicans,95,Golden State Warriors,111
3,2015-10-28,Washington Wizards,88,Orlando Magic,87
4,2015-10-28,Philadelphia 76ers,95,Boston Celtics,112
...,...,...,...,...,...
1225,2016-04-13,Atlanta Hawks,98,Washington Wizards,109
1226,2016-04-13,Memphis Grizzlies,104,Golden State Warriors,125
1227,2016-04-13,Utah Jazz,96,Los Angeles Lakers,101
1228,2016-04-13,Los Angeles Clippers,105,Phoenix Suns,114
1229,2016-04-13,Denver Nuggets,99,Portland Trail Blazers,107

In [32]:
#their largest loss was against the Blazers, on 2016-02-19, so we'll grab all the data of warrior games before this date
season_2016_pre_big_loss = season_2016_df.loc[(season_2016_df["DATE"] < "2016-02-19")]
#a line that didnt work: (team_to_abbreviation[str(season_2016_df["VISITOR"]).upper()] == "GSW" or team_to_abbreviation[str(season_2016_df["HOME"]).upper()] == "GSW")

# warriors_2016_pre_big_loss =  season_2016_pre_big_loss.loc[(team_to_abbreviation[season_2016_df["VISITOR"]] == "Golden State Warriors" | team_to_abbreviation[season_2016_df["HOME"]] == "Golden State Warriors")]

In [10]:
import pandas as pd
# warriors_2016_pre_big_loss = pd.DataFrame()

# for rows in season_2016_pre_big_loss:
#     if ((rows["HOME"] == "Golden State Warriors") or (rows ["VISITOR"] == "Golden State Warriors")):
#         warriors_2016_pre_big_loss.append(rows)
        
warriors_2016_home = season_2016_pre_big_loss.loc[(season_2016_df["HOME"] == "Golden State Warriors")]
warriors_2016_visitor = season_2016_pre_big_loss.loc[(season_2016_df["VISITOR"] == "Golden State Warriors")]

season = [warriors_2016_home, warriors_2016_visitor]

warriors_season = pd.concat(season)

warriors_season=  warriors_season.sort_values(by="DATE", ascending = False)

# warriors_season
last_10_games = pd.DataFrame(warriors_season[0:11])
last_10_games

NameError: name 'season_2016_pre_big_loss' is not defined

In [73]:
last_10_games_stats = []
game_date = last_10_games.iloc[0]["DATE"]
date_no_time = str(game_date).split()[0]
date_no_time

visitor_team = team_to_abbreviation[last_10_games.iloc[0]["VISITOR"].upper()]
visitor_team

home_team = team_to_abbreviation[last_10_games.iloc[0]["HOME"].upper()]
home_team

team_box_score = get_box_scores(date_no_time, visitor_team, home_team, period='GAME', stat_type='BASIC')
team_box_score = pd.DataFrame(team_box_score["GSW"])

team_box_score.tail(1)


# for index, row in last_10_games.iterrows():
#     print("hi")

,PLAYER,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
13,Team Totals,240,37,89,.416,14,40,.350,24,29,...,8,42,50,24,12,7,13,22,112,NaN

In [12]:
def last10Games():
    team = input("Enter the full name of your team: ").title()
    abbreviation = team_to_abbreviation[team.upper()]
    print(f"team abbreviation for {team} is: {abbreviation}")
    
    date = input("Enter a date where you want to look at their stats the last 10 games (YYYY-MM-DD)")
    year = date.split("-")[0]
    print(f"looking up {str(int(year)-1)}-{year} season data before {date}")
    
    season_df = get_schedule(int(year), playoffs=False)
    
    season_before_date_df = season_df.loc[season_df["DATE"] < date] 
    
    team_home_df = season_before_date_df.loc[season_before_date_df["HOME"] == team]
    team_away_df = season_before_date_df.loc[season_before_date_df["VISITOR"] == team]
    
    team_season = [team_home_df, team_away_df]
    team_season_df = pd.concat(team_season).sort_values(by="DATE", ascending=False)
    
    if (len(team_season_df.index) < 10):
        last_10_games = pd.DataFrame(team_season_df[0:])
    else:
        last_10_games = pd.DataFrame(team_season_df[0:10])
        
    last_10_game_data = []
        
    for index, row in last_10_games.iterrows():
        game_date = row["DATE"]
        date_no_time = str(game_date).split()[0]
        
        visitor_team = team_to_abbreviation[row["VISITOR"].upper()]
        home_team = team_to_abbreviation[row["HOME"].upper()]
        
        print(f"getting info on game between: {home_team}(HOME) vs. {visitor_team}(AWAY) on {game_date}")
        
        team_box_score = get_box_scores(date_no_time, visitor_team, home_team, period='GAME', stat_type='BASIC')
        team_box_score = pd.DataFrame(team_box_score[abbreviation]).tail(1)
        
        last_10_game_data.append(team_box_score)
        
    last_10_game_stats = pd.concat(last_10_game_data)
    last_10_game_stats_df = pd.DataFrame(last_10_game_stats)
#     mean = pd.DataFrame(last_10_game_stats_df.mean())
    last_10_game_stats_df.reset_index()
    
    last_10_game_stats_df = last_10_game_stats_df[['FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']]
    
    last_10_game_stats_df["FG"] = last_10_game_stats_df["FG"].astype(int)
    last_10_game_stats_df["FGA"] = last_10_game_stats_df["FGA"].astype(int)
    last_10_game_stats_df["FG%"] = last_10_game_stats_df["FG%"].astype(float)
    last_10_game_stats_df["3P"] = last_10_game_stats_df["3P"].astype(int)
    last_10_game_stats_df["3PA"] = last_10_game_stats_df["3PA"].astype(int)
    last_10_game_stats_df["3P%"] = last_10_game_stats_df["3P%"].astype(float)
    last_10_game_stats_df["FT"] = last_10_game_stats_df["FT"].astype(int)
    last_10_game_stats_df["FTA"] = last_10_game_stats_df["FTA"].astype(int)
    last_10_game_stats_df["FT%"] = last_10_game_stats_df["FT%"].astype(float)
    last_10_game_stats_df["ORB"] = last_10_game_stats_df["ORB"].astype(int)
    last_10_game_stats_df["DRB"] = last_10_game_stats_df["DRB"].astype(int)
    last_10_game_stats_df["TRB"] = last_10_game_stats_df["TRB"].astype(int)
    last_10_game_stats_df["AST"] = last_10_game_stats_df["AST"].astype(int)
    last_10_game_stats_df["STL"] = last_10_game_stats_df["STL"].astype(int)
    last_10_game_stats_df["BLK"] = last_10_game_stats_df["BLK"].astype(int)
    last_10_game_stats_df["TOV"] = last_10_game_stats_df["TOV"].astype(int)
    last_10_game_stats_df["PF"] = last_10_game_stats_df["PF"].astype(int)
    last_10_game_stats_df["PTS"] = last_10_game_stats_df["PTS"].astype(int)

    return last_10_game_stats_df

In [186]:
mean = last10Games()
mean

Enter the full name of your team: golden state warriors
team abbreviation for Golden State Warriors is: GSW
Enter a date where you want to look at their stats the last 10 games (YYYY-MM-DD))2016-02-19
looking up 2015-2016 season data before 2016-02-19
getting info on game between: PHO(HOME) vs. GSW(AWAY) on 2016-02-10 00:00:00
getting info on game between: GSW(HOME) vs. HOU(AWAY) on 2016-02-09 00:00:00
getting info on game between: GSW(HOME) vs. OKC(AWAY) on 2016-02-06 00:00:00
getting info on game between: WAS(HOME) vs. GSW(AWAY) on 2016-02-03 00:00:00
getting info on game between: NYK(HOME) vs. GSW(AWAY) on 2016-01-31 00:00:00
getting info on game between: PHI(HOME) vs. GSW(AWAY) on 2016-01-30 00:00:00
getting info on game between: GSW(HOME) vs. DAL(AWAY) on 2016-01-27 00:00:00
getting info on game between: GSW(HOME) vs. SAS(AWAY) on 2016-01-25 00:00:00
getting info on game between: GSW(HOME) vs. IND(AWAY) on 2016-01-22 00:00:00
getting info on game between: CHI(HOME) vs. GSW(AWAY) on 2016-01-20 00:00:00

,PLAYER,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
13,Team Totals,240,37,89,.416,14,40,.350,24,29,...,8,42,50,24,12,7,13,22,112,NaN
13,Team Totals,240,44,94,.468,12,34,.353,23,26,...,14,35,49,28,5,6,12,26,123,NaN
13,Team Totals,240,48,97,.495,7,26,.269,13,20,...,13,33,46,24,7,4,10,23,116,NaN
13,Team Totals,240,49,93,.527,20,41,.488,16,29,...,11,38,49,35,10,5,18,24,134,NaN
12,Team Totals,240,42,73,.575,16,29,.552,16,23,...,3,41,44,31,8,5,18,21,116,NaN
13,Team Totals,240,47,95,.495,13,30,.433,1,2,...,12,45,57,37,5,7,23,18,108,NaN
13,Team Totals,240,47,81,.580,14,29,.483,19,21,...,7,33,40,33,5,4,9,18,127,NaN
13,Team Totals,240,44,85,.518,11,26,.423,21,25,...,10,35,45,31,15,3,21,25,120,NaN
13,Team Totals,240,43,90,.478,14,33,.424,22,25,...,14,36,50,31,9,4,17,24,122,NaN
13,Team Totals,240,50,95,.526,12,32,.375,13,20,...,12,43,55,38,8,9,10,17,125,NaN

In [187]:
mean.columns

Index(['PLAYER', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       '+/-'],
      dtype='object')

In [188]:
mean = mean[['FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']]
mean

,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
13,37,89,.416,14,40,.350,24,29,.828,8,42,50,24,12,7,13,22,112
13,44,94,.468,12,34,.353,23,26,.885,14,35,49,28,5,6,12,26,123
13,48,97,.495,7,26,.269,13,20,.650,13,33,46,24,7,4,10,23,116
13,49,93,.527,20,41,.488,16,29,.552,11,38,49,35,10,5,18,24,134
12,42,73,.575,16,29,.552,16,23,.696,3,41,44,31,8,5,18,21,116
13,47,95,.495,13,30,.433,1,2,.500,12,45,57,37,5,7,23,18,108
13,47,81,.580,14,29,.483,19,21,.905,7,33,40,33,5,4,9,18,127
13,44,85,.518,11,26,.423,21,25,.840,10,35,45,31,15,3,21,25,120
13,43,90,.478,14,33,.424,22,25,.880,14,36,50,31,9,4,17,24,122
13,50,95,.526,12,32,.375,13,20,.650,12,43,55,38,8,9,10,17,125

In [190]:
mean = mean.reset_index()
mean

,index,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,13,37,89,.416,14,40,.350,24,29,.828,8,42,50,24,12,7,13,22,112
1,13,44,94,.468,12,34,.353,23,26,.885,14,35,49,28,5,6,12,26,123
2,13,48,97,.495,7,26,.269,13,20,.650,13,33,46,24,7,4,10,23,116
3,13,49,93,.527,20,41,.488,16,29,.552,11,38,49,35,10,5,18,24,134
4,12,42,73,.575,16,29,.552,16,23,.696,3,41,44,31,8,5,18,21,116
5,13,47,95,.495,13,30,.433,1,2,.500,12,45,57,37,5,7,23,18,108
6,13,47,81,.580,14,29,.483,19,21,.905,7,33,40,33,5,4,9,18,127
7,13,44,85,.518,11,26,.423,21,25,.840,10,35,45,31,15,3,21,25,120
8,13,43,90,.478,14,33,.424,22,25,.880,14,36,50,31,9,4,17,24,122
9,13,50,95,.526,12,32,.375,13,20,.650,12,43,55,38,8,9,10,17,125

In [191]:
mean["FG"] = mean["FG"].astype(int)
mean["FGA"] = mean["FGA"].astype(int)
mean["FG%"] = mean["FG%"].astype(float)
mean["3P"] = mean["3P"].astype(int)
mean["3PA"] = mean["3PA"].astype(int)
mean["3P%"] = mean["3P%"].astype(float)
mean["FT"] = mean["FT"].astype(int)
mean["FTA"] = mean["FTA"].astype(int)
mean["FT%"] = mean["FT%"].astype(float)
mean["ORB"] = mean["ORB"].astype(int)
mean["DRB"] = mean["DRB"].astype(int)
mean["TRB"] = mean["TRB"].astype(int)
mean["AST"] = mean["AST"].astype(int)
mean["STL"] = mean["STL"].astype(int)
mean["BLK"] = mean["BLK"].astype(int)
mean["TOV"] = mean["TOV"].astype(int)
mean["PF"] = mean["PF"].astype(int)
mean["PTS"] = mean["PTS"].astype(int)

In [192]:
mean.dtypes

index      int64
FG         int64
FGA        int64
FG%      float64
3P         int64
3PA        int64
3P%      float64
FT         int64
FTA        int64
FT%      float64
ORB        int64
DRB        int64
TRB        int64
AST        int64
STL        int64
BLK        int64
TOV        int64
PF         int64
PTS        int64
dtype: object

In [193]:
mean.mean()

index     12.9000
FG        45.1000
FGA       89.2000
FG%        0.5078
3P        13.3000
3PA       32.0000
3P%        0.4150
FT        16.8000
FTA       22.0000
FT%        0.7386
ORB       10.4000
DRB       38.1000
TRB       48.5000
AST       31.2000
STL        8.4000
BLK        5.4000
TOV       15.1000
PF        21.8000
PTS      120.3000
dtype: float64

In [194]:
mean["ORB"].sum()

104

In [13]:
gsw = last10Games()

Enter the full name of your team: golden state warriors
team abbreviation for Golden State Warriors is: GSW
Enter a date where you want to look at their stats the last 10 games (YYYY-MM-DD)2016-02-19
looking up 2015-2016 season data before 2016-02-19
getting info on game between: PHO(HOME) vs. GSW(AWAY) on 2016-02-10 00:00:00
getting info on game between: GSW(HOME) vs. HOU(AWAY) on 2016-02-09 00:00:00
getting info on game between: GSW(HOME) vs. OKC(AWAY) on 2016-02-06 00:00:00
getting info on game between: WAS(HOME) vs. GSW(AWAY) on 2016-02-03 00:00:00
getting info on game between: NYK(HOME) vs. GSW(AWAY) on 2016-01-31 00:00:00
getting info on game between: PHI(HOME) vs. GSW(AWAY) on 2016-01-30 00:00:00
getting info on game between: GSW(HOME) vs. DAL(AWAY) on 2016-01-27 00:00:00
getting info on game between: GSW(HOME) vs. SAS(AWAY) on 2016-01-25 00:00:00
getting info on game between: GSW(HOME) vs. IND(AWAY) on 2016-01-22 00:00:00
getting info on game between: CHI(HOME) vs. GSW(AWAY) on 2016-01-20 00:00:00

In [200]:
por = last10Games()

Enter the full name of your team: portland trail blazers
team abbreviation for Portland Trail Blazers is: POR
Enter a date where you want to look at their stats the last 10 games (YYYY-MM-DD))2016-02-19
looking up 2015-2016 season data before 2016-02-19
getting info on game between: POR(HOME) vs. HOU(AWAY) on 2016-02-10 00:00:00
getting info on game between: MEM(HOME) vs. POR(AWAY) on 2016-02-08 00:00:00
getting info on game between: HOU(HOME) vs. POR(AWAY) on 2016-02-06 00:00:00
getting info on game between: POR(HOME) vs. TOR(AWAY) on 2016-02-04 00:00:00
getting info on game between: POR(HOME) vs. MIL(AWAY) on 2016-02-02 00:00:00
getting info on game between: POR(HOME) vs. MIN(AWAY) on 2016-01-31 00:00:00
getting info on game between: POR(HOME) vs. CHO(AWAY) on 2016-01-29 00:00:00
getting info on game between: POR(HOME) vs. SAC(AWAY) on 2016-01-26 00:00:00
getting info on game between: POR(HOME) vs. LAL(AWAY) on 2016-01-23 00:00:00
getting info on game between: POR(HOME) vs. ATL(AWAY) on 2016-01-20 00:00:00

In [198]:
gsw.mean()

FG      45.1000
FGA     89.2000
FG%      0.5078
3P      13.3000
3PA     32.0000
3P%      0.4150
FT      16.8000
FTA     22.0000
FT%      0.7386
ORB     10.4000
DRB     38.1000
TRB     48.5000
AST     31.2000
STL      8.4000
BLK      5.4000
TOV     15.1000
PF      21.8000
PTS    120.3000
dtype: float64

In [201]:
por.mean()

FG      40.6000
FGA     87.6000
FG%      0.4625
3P       9.1000
3PA     28.7000
3P%      0.3185
FT      16.7000
FTA     22.3000
FT%      0.7391
ORB     12.2000
DRB     33.5000
TRB     45.7000
AST     22.7000
STL      8.9000
BLK      4.9000
TOV     13.2000
PF      21.9000
PTS    107.0000
dtype: float64

In [14]:
gsw

,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
13,37,89,0.416,14,40,0.350,24,29,0.828,8,42,50,24,12,7,13,22,112
13,44,94,0.468,12,34,0.353,23,26,0.885,14,35,49,28,5,6,12,26,123
13,48,97,0.495,7,26,0.269,13,20,0.650,13,33,46,24,7,4,10,23,116
13,49,93,0.527,20,41,0.488,16,29,0.552,11,38,49,35,10,5,18,24,134
12,42,73,0.575,16,29,0.552,16,23,0.696,3,41,44,31,8,5,18,21,116
13,47,95,0.495,13,30,0.433,1,2,0.500,12,45,57,37,5,7,23,18,108
13,47,81,0.580,14,29,0.483,19,21,0.905,7,33,40,33,5,4,9,18,127
13,44,85,0.518,11,26,0.423,21,25,0.840,10,35,45,31,15,3,21,25,120
13,43,90,0.478,14,33,0.424,22,25,0.880,14,36,50,31,9,4,17,24,122
13,50,95,0.526,12,32,0.375,13,20,0.650,12,43,55,38,8,9,10,17,125

In [28]:
def seasonData():
    team = input("Enter the full name of your team: ").title()
    abbreviation = team_to_abbreviation[team.upper()]
    print(f"team abbreviation for {team} is: {abbreviation}")
    
    date = input("Enter a date where you want to look at their stats the last 10 games (YYYY-MM-DD)")
    year = input("Enter the end year of the season you want to look for: ")

    
    season_df = get_schedule(int(year), playoffs=False)
    
    season_before_date_df = season_df.loc[season_df["DATE"] < date] 
    
    team_home_df = season_before_date_df.loc[season_before_date_df["HOME"] == team]
    team_away_df = season_before_date_df.loc[season_before_date_df["VISITOR"] == team]
    
    team_season = [team_home_df, team_away_df]
    team_season_df = pd.concat(team_season).sort_values(by="DATE", ascending=False)
        
    season_data = []
    win_loss = []
        
    for index, row in pd.DataFrame(team_season_df).iterrows():
        game_date = row["DATE"]
        date_no_time = str(game_date).split()[0]
        
        visitor_team = team_to_abbreviation[row["VISITOR"].upper()]
        home_team = team_to_abbreviation[row["HOME"].upper()]
        
        if int(row["HOME_PTS"]) > int(row["VISITOR_PTS"]):
            home_result = "W"
            away_result = "L"
        else:
            home_result = "L"
            away_result = "W"
            
        team_result = (home_result if home_team == abbreviation else away_result)
        
        print(f"getting info on game between: {home_team}(HOME){home_result} vs. {visitor_team}(AWAY){away_result} on {game_date}")
        
        team_box_score = get_box_scores(date_no_time, visitor_team, home_team, period='GAME', stat_type='BASIC')
        team_box_score = pd.DataFrame(team_box_score[abbreviation]).tail(1)
        
        season_data.append(team_box_score)
        win_loss.append(team_result)
        
    season_stats = pd.concat(season_data)
    season_stats_df = pd.DataFrame(season_stats)
#     mean = pd.DataFrame(last_10_game_stats_df.mean())
    season_stats_df.reset_index()
    
    season_stats_df = season_stats_df[['FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']]
    
    season_stats_df["FG"] = season_stats_df["FG"].astype(int)
    season_stats_df["FGA"] = season_stats_df["FGA"].astype(int)
    season_stats_df["FG%"] = season_stats_df["FG%"].astype(float)
    season_stats_df["3P"] = season_stats_df["3P"].astype(int)
    season_stats_df["3PA"] = season_stats_df["3PA"].astype(int)
    season_stats_df["3P%"] = season_stats_df["3P%"].astype(float)
    season_stats_df["FT"] = season_stats_df["FT"].astype(int)
    season_stats_df["FTA"] = season_stats_df["FTA"].astype(int)
    season_stats_df["FT%"] = season_stats_df["FT%"].astype(float)
    season_stats_df["ORB"] = season_stats_df["ORB"].astype(int)
    season_stats_df["DRB"] = season_stats_df["DRB"].astype(int)
    season_stats_df["TRB"] = season_stats_df["TRB"].astype(int)
    season_stats_df["AST"] = season_stats_df["AST"].astype(int)
    season_stats_df["STL"] = season_stats_df["STL"].astype(int)
    season_stats_df["BLK"] = season_stats_df["BLK"].astype(int)
    season_stats_df["TOV"] = season_stats_df["TOV"].astype(int)
    season_stats_df["PF"] = season_stats_df["PF"].astype(int)
    season_stats_df["PTS"] = season_stats_df["PTS"].astype(int)
    
    print(str(win_loss))

    return season_stats_df

# ANALYZING THE 73-9 2015-2016 WARRIORS

In [29]:
gsw_szn = seasonData()

Enter the full name of your team: golden state warriors
team abbreviation for Golden State Warriors is: GSW
Enter a date where you want to look at their stats the last 10 games (YYYY-MM-DD)2016-02-19
Enter the end year of the season you want to look for: 2016
getting info on game between: PHO(HOME)L vs. GSW(AWAY)W on 2016-02-10 00:00:00
getting info on game between: GSW(HOME)W vs. HOU(AWAY)L on 2016-02-09 00:00:00
getting info on game between: GSW(HOME)W vs. OKC(AWAY)L on 2016-02-06 00:00:00
getting info on game between: WAS(HOME)L vs. GSW(AWAY)W on 2016-02-03 00:00:00
getting info on game between: NYK(HOME)L vs. GSW(AWAY)W on 2016-01-31 00:00:00
getting info on game between: PHI(HOME)L vs. GSW(AWAY)W on 2016-01-30 00:00:00
getting info on game between: GSW(HOME)W vs. DAL(AWAY)L on 2016-01-27 00:00:00
getting info on game between: GSW(HOME)W vs. SAS(AWAY)L on 2016-01-25 00:00:00
getting info on game between: GSW(HOME)W vs. IND(AWAY)L on 2016-01-22 00:00:00
getting info on game between: CHI(HOME)L vs. GSW(AWAY)W on 2016-01-20 00:00:00
getting info on game between: CLE(HOME)L vs. GSW(AWAY)W on 2016-01-18 00:00:00
getting info on game between: DET(HOME)W vs. GSW(AWAY)L on 2016-01-16 00:00:00
getting info on game between: GSW(HOME)W vs. LAL(AWAY)L on 2016-01-14 00:00:00
getting info on game between: DEN(HOME)W vs. GSW(AWAY)L on 2016-01-13 00:00:00
getting info on game between: GSW(HOME)W vs. MIA(AWAY)L on 2016-01-11 00:00:00
getting info on game between: SAC(HOME)L vs. GSW(AWAY)W on 2016-01-09 00:00:00
getting info on game between: POR(HOME)L vs. GSW(AWAY)W on 2016-01-08 00:00:00
getting info on game between: LAL(HOME)L vs. GSW(AWAY)W on 2016-01-05 00:00:00
getting info on game between: GSW(HOME)W vs. CHO(AWAY)L on 2016-01-04 00:00:00
getting info on game between: GSW(HOME)W vs. DEN(AWAY)L on 2016-01-02 00:00:00
getting info on game between: HOU(HOME)L vs. GSW(AWAY)W on 2015-12-31 00:00:00
getting info on game between: DAL(HOME)W vs. GSW(AWAY)L on 2015-12-30 00:00:00
getting info on game between: GSW(HOME)W vs. SAC(AWAY)L on 2015-12-28 00:00:00
getting info on game between: GSW(HOME)W vs. CLE(AWAY)L on 2015-12-25 00:00:00
getting info on game between: GSW(HOME)W vs. UTA(AWAY)L on 2015-12-23 00:00:00
getting info on game between: GSW(HOME)W vs. MIL(AWAY)L on 2015-12-18 00:00:00
getting info on game between: GSW(HOME)W vs. PHO(AWAY)L on 2015-12-16 00:00:00
getting info on game between: MIL(HOME)W vs. GSW(AWAY)L on 2015-12-12 00:00:00
getting info on game between: BOS(HOME)L vs. GSW(AWAY)W on 2015-12-11 00:00:00
getting info on game between: IND(HOME)L vs. GSW(AWAY)W on 2015-12-08 00:00:00
getting info on game between: BRK(HOME)L vs. GSW(AWAY)W on 2015-12-06 00:00:00
getting info on game between: TOR(HOME)L vs. GSW(AWAY)W on 2015-12-05 00:00:00
getting info on game between: CHO(HOME)L vs. GSW(AWAY)W on 2015-12-02 00:00:00
getting info on game between: UTA(HOME)L vs. GSW(AWAY)W on 2015-11-30 00:00:00
getting info on game between: GSW(HOME)W vs. SAC(AWAY)L on 2015-11-28 00:00:00
getting info on game between: PHO(HOME)L vs. GSW(AWAY)W on 2015-11-27 00:00:00
getting info on game between: GSW(HOME)W vs. LAL(AWAY)L on 2015-11-24 00:00:00
getting info on game between: DEN(HOME)L vs. GSW(AWAY)W on 2015-11-22 00:00:00
getting info on game between: GSW(HOME)W vs. CHI(AWAY)L on 2015-11-20 00:00:00
getting info on game between: LAC(HOME)L vs. GSW(AWAY)W on 2015-11-19 00:00:00
getting info on game between: GSW(HOME)W vs. TOR(AWAY)L on 2015-11-17 00:00:00
getting info on game between: GSW(HOME)W vs. BRK(AWAY)L on 2015-11-14 00:00:00
getting info on game between: MIN(HOME)L vs. GSW(AWAY)W on 2015-11-12 00:00:00
getting info on game between: MEM(HOME)L vs. GSW(AWAY)W on 2015-11-11 00:00:00
getting info on game between: GSW(HOME)W vs. DET(AWAY)L on 2015-11-09 00:00:00
getting info on game between: SAC(HOME)L vs. GSW(AWAY)W on 2015-11-07 00:00:00
getting info on game between: GSW(HOME)W vs. DEN(AWAY)L on 2015-11-06 00:00:00
getting info on game between: GSW(HOME)W vs. LAC(AWAY)L on 2015-11-04 00:00:00
getting info on game between: GSW(HOME)W vs. MEM(AWAY)L on 2015-11-02 00:00:00
getting info on game between: NOP(HOME)L vs. GSW(AWAY)W on 2015-10-31 00:00:00
getting info on game between: HOU(HOME)L vs. GSW(AWAY)W on 2015-10-30 00:00:00
getting info on game between: GSW(HOME)W vs. NOP(AWAY)L on 2015-10-27 00:00:00
['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'L', 'W', 'L', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']

In [26]:
gsw_szn

,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
13,37,89,0.416,14,40,0.350,24,29,0.828,8,42,50,24,12,7,13,22,112
13,44,94,0.468,12,34,0.353,23,26,0.885,14,35,49,28,5,6,12,26,123
13,48,97,0.495,7,26,0.269,13,20,0.650,13,33,46,24,7,4,10,23,116
13,49,93,0.527,20,41,0.488,16,29,0.552,11,38,49,35,10,5,18,24,134
12,42,73,0.575,16,29,0.552,16,23,0.696,3,41,44,31,8,5,18,21,116
13,47,95,0.495,13,30,0.433,1,2,0.500,12,45,57,37,5,7,23,18,108
13,47,81,0.580,14,29,0.483,19,21,0.905,7,33,40,33,5,4,9,18,127
13,44,85,0.518,11,26,0.423,21,25,0.840,10,35,45,31,15,3,21,25,120
13,43,90,0.478,14,33,0.424,22,25,0.880,14,36,50,31,9,4,17,24,122
13,50,95,0.526,12,32,0.375,13,20,0.650,12,43,55,38,8,9,10,17,125
13,46,85,0.541,19,40,0.475,21,27,0.778,6,31,37,33,7,2,8,25,132
13,34,94,0.362,10,25,0.400,17,23,0.739,14,33,47,18,6,9,12,16,95
13,43,86,0.500,13,33,0.394,17,20,0.850,12,35,47,26,12,4,19,17,116
13,42,88,0.477,10,26,0.385,16,20,0.800,7,32,39,25,9,11,13,25,110
13,41,86,0.477,7,23,0.304,22,30,0.733,9,40,49,25,5,1,9,18,111
13,49,87,0.563,19,37,0.514,11,15,0.733,9,39,48,35,5,8,18,25,128
13,46,87,0.529,18,32,0.563,18,21,0.857,5,43,48,36,6,5,15,20,128
13,40,86,0.465,13,31,0.419,16,21,0.762,10,44,54,26,9,9,10,17,109
13,45,87,0.517,15,34,0.441,6,6,1.000,3,34,37,32,4,9,11,19,111
13,43,86,0.500,10,28,0.357,15,23,0.652,9,38,47,34,9,5,13,22,111
13,43,84,0.512,11,23,0.478,17,27,0.630,12,31,43,35,8,5,18,20,114
13,33,81,0.407,7,19,0.368,18,24,0.750,8,29,37,20,9,0,12,18,91
13,43,89,0.483,20,42,0.476,16,24,0.667,13,46,59,33,12,8,18,25,122
13,32,78,0.410,5,18,0.278,20,27,0.741,8,41,49,21,7,10,16,19,89
13,39,83,0.470,9,23,0.391,16,16,1.000,9,31,40,26,10,9,15,11,103
13,42,87,0.483,9,26,0.346,28,37,0.757,15,31,46,31,7,4,15,22,121
13,46,88,0.523,15,32,0.469,21,27,0.778,9,40,49,32,12,4,17,17,128
13,36,89,0.404,6,27,0.222,17,25,0.680,15,34,49,23,9,8,16,20,95
13,42,107,0.393,9,31,0.290,31,39,0.795,17,50,67,28,10,11,18,22,124
13,52,95,0.547,16,35,0.457,11,15,0.733,10,36,46,29,10,6,15,19,131
13,44,86,0.512,14,33,0.424,12,23,0.522,10,36,46,25,9,9,12,18,114
13,35,73,0.479,16,30,0.533,26,36,0.722,8,35,43,22,2,5,12,24,112
13,46,88,0.523,16,34,0.471,8,11,0.727,11,42,53,31,2,9,18,23,116
13,40,82,0.488,14,29,0.483,12,15,0.800,14,31,45,21,2,5,15,19,106
13,39,80,0.488,16,30,0.533,26,31,0.839,13,35,48,32,8,7,14,19,120
13,46,81,0.568,22,38,0.579,21,31,0.677,11,42,53,32,7,9,23,26,135
13,45,92,0.489,12,35,0.343,9,15,0.600,12,36,48,32,9,6,8,13,111
13,47,89,0.528,15,29,0.517,9,13,0.692,11,35,46,35,15,8,21,25,118
13,39,79,0.494,10,29,0.345,18,24,0.750,11,38,49,20,7,6,15,15,106
13,38,73,0.521,17,30,0.567,31,36,0.861,8,36,44,31,4,4,19,20,124
13,43,80,0.538,11,29,0.379,18,27,0.667,9,25,34,31,10,6,20,29,115
13,43,97,0.443,12,34,0.353,9,10,0.900,11,39,50,31,9,10,14,19,107
13,48,89,0.539,18,38,0.474,15,16,0.938,6,27,33,34,8,7,11,25,129
13,36,75,0.480,11,27,0.407,17,23,0.739,7,29,36,22,12,8,23,30,100
13,43,91,0.473,12,21,0.571,11,13,0.846,13,28,41,29,13,4,16,18,109
13,38,92,0.413,8,39,0.205,19,22,0.864,15,31,46,27,13,2,18,15,103
13,46,93,0.495,17,37,0.459,10,18,0.556,13,40,53,40,10,6,20,22,119
13,39,85,0.459,10,26,0.385,24,31,0.774,9,33,42,28,6,5,12,22,112
13,43,84,0.512,11,25,0.440,22,30,0.733,10,55,65,32,8,13,14,15,119
13,46,84,0.548,17,30,0.567,25,35,0.714,3,35,38,26,10,4,10,24,134
13,43,93,0.462,9,26,0.346,17,25,0.680,11,36,47,26,9,4,8,24,112
13,41,96,0.427,9,30,0.300,20,22,0.909,21,35,56,29,8,7,20,29,111

# AI Portion

In [34]:
# X = voice.drop("label", axis=1)
# y = voice["label"].values.reshape(-1,1)
# print(X.shape, y.shape)
import numpy

X = gsw_szn
y=numpy.array(['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'L', 'W', 'L', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']).reshape(-1,1)

print(X.shape, y.shape)

(52, 18) (52, 1)

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [36]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression()

In [37]:
classifier.fit(X_train, y_train)

/Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [38]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.8461538461538461

In [44]:
predictions = classifier.predict(X_test)
print(f"Season Predictions:   {predictions[:]}")
print(f"Actual labels: {y_test[:10].tolist()}")

Season Predictions:   ['W' 'L' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W' 'W']
Actual labels: [['W'], ['W'], ['W'], ['W'], ['W'], ['W'], ['W'], ['W'], ['W'], ['W']]

# looking at the denver nuggets team that came back from 3-1 deficits last year consecutively

In [45]:
denver_szn = seasonData()

Enter the full name of your team: Denver Nuggets
team abbreviation for Denver Nuggets is: DEN
Enter a date where you want to look at their stats the last 10 games (YYYY-MM-DD)2020-02-28
Enter the end year of the season you want to look for: 2020
getting info on game between: DEN(HOME)W vs. DET(AWAY)L on 2020-02-25 00:00:00
getting info on game between: DEN(HOME)W vs. MIN(AWAY)L on 2020-02-23 00:00:00
getting info on game between: OKC(HOME)W vs. DEN(AWAY)L on 2020-02-21 00:00:00
getting info on game between: DEN(HOME)L vs. LAL(AWAY)W on 2020-02-12 00:00:00
getting info on game between: DEN(HOME)W vs. SAS(AWAY)L on 2020-02-10 00:00:00
getting info on game between: PHO(HOME)L vs. DEN(AWAY)W on 2020-02-08 00:00:00
getting info on game between: UTA(HOME)L vs. DEN(AWAY)W on 2020-02-05 00:00:00
getting info on game between: DEN(HOME)W vs. POR(AWAY)L on 2020-02-04 00:00:00
getting info on game between: DET(HOME)W vs. DEN(AWAY)L on 2020-02-02 00:00:00
getting info on game between: MIL(HOME)L vs. DEN(AWAY)W on 2020-01-31 00:00:00
getting info on game between: DEN(HOME)W vs. UTA(AWAY)L on 2020-01-30 00:00:00
getting info on game between: MEM(HOME)W vs. DEN(AWAY)L on 2020-01-28 00:00:00
getting info on game between: DEN(HOME)W vs. HOU(AWAY)L on 2020-01-26 00:00:00
getting info on game between: NOP(HOME)L vs. DEN(AWAY)W on 2020-01-24 00:00:00
getting info on game between: HOU(HOME)W vs. DEN(AWAY)L on 2020-01-22 00:00:00
getting info on game between: MIN(HOME)L vs. DEN(AWAY)W on 2020-01-20 00:00:00
getting info on game between: DEN(HOME)L vs. IND(AWAY)W on 2020-01-19 00:00:00
getting info on game between: GSW(HOME)L vs. DEN(AWAY)W on 2020-01-16 00:00:00
getting info on game between: DEN(HOME)W vs. CHO(AWAY)L on 2020-01-15 00:00:00
getting info on game between: DEN(HOME)W vs. LAC(AWAY)L on 2020-01-12 00:00:00
getting info on game between: DEN(HOME)L vs. CLE(AWAY)W on 2020-01-11 00:00:00
getting info on game between: DAL(HOME)L vs. DEN(AWAY)W on 2020-01-08 00:00:00
getting info on game between: ATL(HOME)L vs. DEN(AWAY)W on 2020-01-06 00:00:00
getting info on game between: WAS(HOME)W vs. DEN(AWAY)L on 2020-01-04 00:00:00
getting info on game between: IND(HOME)L vs. DEN(AWAY)W on 2020-01-02 00:00:00
getting info on game between: HOU(HOME)W vs. DEN(AWAY)L on 2019-12-31 00:00:00
getting info on game between: DEN(HOME)W vs. SAC(AWAY)L on 2019-12-29 00:00:00
getting info on game between: DEN(HOME)W vs. MEM(AWAY)L on 2019-12-28 00:00:00
getting info on game between: DEN(HOME)L vs. NOP(AWAY)W on 2019-12-25 00:00:00
getting info on game between: PHO(HOME)L vs. DEN(AWAY)W on 2019-12-23 00:00:00
getting info on game between: LAL(HOME)L vs. DEN(AWAY)W on 2019-12-22 00:00:00
getting info on game between: DEN(HOME)W vs. MIN(AWAY)L on 2019-12-20 00:00:00
getting info on game between: DEN(HOME)W vs. ORL(AWAY)L on 2019-12-18 00:00:00
getting info on game between: DEN(HOME)W vs. NYK(AWAY)L on 2019-12-15 00:00:00
getting info on game between: DEN(HOME)W vs. OKC(AWAY)L on 2019-12-14 00:00:00
getting info on game between: DEN(HOME)W vs. POR(AWAY)L on 2019-12-12 00:00:00
getting info on game between: PHI(HOME)W vs. DEN(AWAY)L on 2019-12-10 00:00:00
getting info on game between: BRK(HOME)W vs. DEN(AWAY)L on 2019-12-08 00:00:00
getting info on game between: BOS(HOME)W vs. DEN(AWAY)L on 2019-12-06 00:00:00
getting info on game between: NYK(HOME)L vs. DEN(AWAY)W on 2019-12-05 00:00:00
getting info on game between: DEN(HOME)L vs. LAL(AWAY)W on 2019-12-03 00:00:00
getting info on game between: SAC(HOME)W vs. DEN(AWAY)L on 2019-11-30 00:00:00
getting info on game between: DEN(HOME)W vs. WAS(AWAY)L on 2019-11-26 00:00:00
getting info on game between: DEN(HOME)W vs. PHO(AWAY)L on 2019-11-24 00:00:00
getting info on game between: DEN(HOME)W vs. BOS(AWAY)L on 2019-11-22 00:00:00
getting info on game between: DEN(HOME)W vs. HOU(AWAY)L on 2019-11-20 00:00:00
getting info on game between: MEM(HOME)L vs. DEN(AWAY)W on 2019-11-17 00:00:00
getting info on game between: DEN(HOME)W vs. BRK(AWAY)L on 2019-11-14 00:00:00
getting info on game between: DEN(HOME)L vs. ATL(AWAY)W on 2019-11-12 00:00:00
getting info on game between: MIN(HOME)L vs. DEN(AWAY)W on 2019-11-10 00:00:00
getting info on game between: DEN(HOME)W vs. PHI(AWAY)L on 2019-11-08 00:00:00
getting info on game between: DEN(HOME)W vs. MIA(AWAY)L on 2019-11-05 00:00:00
getting info on game between: ORL(HOME)L vs. DEN(AWAY)W on 2019-11-02 00:00:00
getting info on game between: NOP(HOME)W vs. DEN(AWAY)L on 2019-10-31 00:00:00
getting info on game between: DEN(HOME)L vs. DAL(AWAY)W on 2019-10-29 00:00:00
getting info on game between: SAC(HOME)L vs. DEN(AWAY)W on 2019-10-28 00:00:00
getting info on game between: DEN(HOME)W vs. PHO(AWAY)L on 2019-10-25 00:00:00
getting info on game between: POR(HOME)L vs. DEN(AWAY)W on 2019-10-23 00:00:00
['W', 'W', 'L', 'L', 'W', 'W', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'L', 'W', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'L', 'L', 'L', 'W', 'L', 'L', 'W', 'W', 'W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'L', 'L', 'W', 'W', 'W']

In [ ]:
denver_szn

In [49]:
import numpy

X = denver_szn
y=numpy.array(['W', 'W', 'L', 'L', 'W', 'W', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'L', 'W', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'L', 'L', 'L', 'W', 'L', 'L', 'W', 'W', 'W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'L', 'L', 'W', 'W', 'W']).reshape(-1,1)
print(X.shape, y.shape)

(58, 18) (58, 1)

In [50]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [51]:
classifier.fit(X_train, y_train)

/Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [52]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.9534883720930233
Testing Data Score: 0.7333333333333333

In [53]:
predictions = classifier.predict(X_test)
print(f"Season Predictions:   {predictions[:]}")
print(f"Actual labels: {y_test[:10].tolist()}")

Season Predictions:   ['L' 'W' 'W' 'W' 'W' 'L' 'L' 'W' 'W' 'W' 'W' 'W' 'W' 'L' 'W']
Actual labels: [['L'], ['L'], ['W'], ['W'], ['W'], ['W'], ['L'], ['W'], ['W'], ['W']]