In [1]:
pip install basketball-reference-scraper

Requirement already satisfied: basketball-reference-scraper in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (1.0.26)
Requirement already satisfied: soupsieve==1.9.5 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (1.9.5)
Requirement already satisfied: beautifulsoup4==4.8.2 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (4.8.2)
Requirement already satisfied: requests==2.22.0 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (2.22.0)
Requirement already satisfied: pandas==0.25.3 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (0.25.3)
Requirement already satisfied: numpy==1.18.1 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (1.18.1)
Requirement already satisfied: python-dateutil==2.8.1 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (2.8.1)
Requirement already satisfied: pytz==2019.3 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (2019.3)
Requirement already satisfied: lxml==4.4.2 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (4.4.2)
Requirement already satisfied: bs4==0.0.1 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (0.0.1)
Requirement already satisfied: six==1.13.0 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (1.13.0)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (1.25.9)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats, get_team_misc

In [3]:
s = get_team_stats('GSW', 2019, data_format='PER_GAME')
print(s)

G              82
MP          241.5
FG             44
FGA          89.8
FG%         0.491
3P           13.3
3PA          34.4
3P%         0.385
2P           30.8
2PA          55.3
2P%         0.557
FT           16.3
FTA          20.4
FT%         0.801
ORB           9.7
DRB          36.5
TRB          46.2
AST          29.4
STL           7.6
BLK           6.4
TOV          14.3
PF           21.4
PTS         117.7
TEAM          GSW
SEASON    2018-19
dtype: object

In [4]:
s = get_opp_stats('GSW', 2019, data_format='PER_GAME')
print(s)

OPP_G           82
OPP_MP       241.5
OPP_FG        40.4
OPP_FGA       91.1
OPP_FG%      0.444
OPP_3P        11.6
OPP_3PA       33.6
OPP_3P%      0.347
OPP_2P        28.8
OPP_2PA       57.5
OPP_2P%        0.5
OPP_FT        18.7
OPP_FTA       24.2
OPP_FT%      0.773
OPP_ORB       10.8
OPP_DRB       33.5
OPP_TRB       44.3
OPP_AST       24.3
OPP_STL        7.7
OPP_BLK        3.6
OPP_TOV       13.5
OPP_PF        19.5
OPP_PTS      111.2
TEAM           GSW
SEASON     2018-19
dtype: object

In [5]:
from basketball_reference_scraper.box_scores import get_box_scores

s = get_box_scores('2020-01-13', 'CHI', 'BOS', period='GAME', stat_type='BASIC')
print(s)

{'CHI':                 PLAYER     MP  FG FGA    FG% 3P 3PA    3P%  FT FTA  ... ORB  \
0          Zach LaVine  34:52   9  18   .500  3   6   .500   9   9  ...   1
1            Kris Dunn  30:01   3   7   .429  1   2   .500   2   3  ...   0
2     Tomáš Satoranský  25:55   3   8   .375  0   1   .000   6   8  ...   1
3      Lauri Markkanen  25:20   4   9   .444  0   3   .000   1   2  ...   1
4       Daniel Gafford  20:24   4   5   .800  0   0    NaN   2   2  ...   2
5       Thaddeus Young  24:23   8  14   .571  1   4   .250   0   0  ...   0
6           Coby White  23:23   3   8   .375  0   4   .000   0   0  ...   1
7          Luke Kornet  21:53   0   2   .000  0   2   .000   0   0  ...   0
8   Chandler Hutchison  14:24   1   5   .200  0   0    NaN   0   0  ...   1
9     Ryan Arcidiacono  13:25   0   2   .000  0   2   .000   0   0  ...   0
10    Denzel Valentine   2:00   2   2  1.000  1   1  1.000   0   0  ...   0
11  Shaquille Harrison   2:00   0   1   .000  0   0    NaN   1   2  ...   0
12   Cristiano Felício   2:00   0   0    NaN  0   0    NaN   0   0  ...   0
13         Team Totals    240  37  81   .457  6  25   .240  21  26  ...   7

   DRB TRB AST STL BLK TOV  PF  PTS  +/-
0    4   5   2   1   0   6   3   30   -7
1    5   5   1   0   0   2   2    9   -5
2    0   1   7   1   0   2   2   12   +3
3    5   6   0   2   0   0   3    9   -5
4    1   3   1   0   2   0   4   10   +8
5    2   2   1   0   0   1   1   17  -11
6    2   3   4   0   0   1   1    6  -18
7    5   5   0   0   1   1   2    0  -24
8    2   3   0   1   2   1   2    2   -6
9    3   3   0   0   0   0   2    0   -7
10   1   1   0   0   0   0   0    5   +4
11   1   1   0   0   0   0   0    1   +4
12   0   0   0   0   0   0   0    0   +4
13  31  38  16   5   5  14  22  101  NaN

[14 rows x 21 columns], 'BOS':              PLAYER     MP  FG FGA   FG% 3P 3PA    3P%  FT FTA  ... ORB DRB  \
0      Jaylen Brown  30:15   5  13  .385  0   1   .000   9   9  ...   2   1
1    Gordon Hayward  30:09   4  11  .364  0   1   .000   0   0  ...   0   6
2      Jayson Tatum  29:43   7  17  .412  2   7   .286   5   7  ...   0   6
3      Kemba Walker  27:36   5   9  .556  3   6   .500   1   2  ...   0   4
4       Enes Kanter  26:27   7   9  .778  0   0    NaN   1   1  ...   2   7
5      Marcus Smart  33:24   4   8  .500  2   5   .400   2   2  ...   0   5
6    Brad Wanamaker  24:11   3   5  .600  1   1  1.000   2   2  ...   1   2
7    Grant Williams  16:17   4   8  .500  1   2   .500   2   2  ...   4   1
8      Semi Ojeleye  12:57   0   0   NaN  0   0    NaN   0   0  ...   1   0
9   Vincent Poirier   5:01   0   3  .000  0   0    NaN   2   2  ...   0   0
10   Romeo Langford   2:00   0   0   NaN  0   0    NaN   2   2  ...   0   0
11    Javonte Green   2:00   0   0   NaN  0   0    NaN   0   0  ...   0   1
12      Team Totals    240  39  83  .470  9  23   .391  26  29  ...  10  33

   TRB AST STL BLK TOV  PF  PTS  +/-
0    3   3   2   0   0   3   19  +10
1    6   8   0   0   1   3    8  +14
2    6   2   1   2   1   1   21   -2
3    4   2   0   2   2   1   14   +2
4    9   0   1   1   5   3   15   +4
5    5   8   3   0   1   3   12  +25
6    3   2   0   0   0   1    9   +7
7    5   3   0   1   1   2   11  +11
8    1   0   0   0   0   0    0    0
9    0   0   0   0   1   2    2   -3
10   0   0   0   0   0   0    2   -4
11   1   0   0   0   0   0    0   -4
12  43  28   7   6  12  19  113  NaN

[13 rows x 21 columns]}

In [6]:
from basketball_reference_scraper.seasons import get_schedule, get_standings

s = get_schedule(2020, playoffs=False)
print(s)

           DATE                VISITOR  VISITOR_PTS                    HOME  \
0    2019-10-22   New Orleans Pelicans          122         Toronto Raptors
1    2019-10-22     Los Angeles Lakers          102    Los Angeles Clippers
2    2019-10-23         Denver Nuggets          108  Portland Trail Blazers
3    2019-10-23       Sacramento Kings           95            Phoenix Suns
4    2019-10-23  Oklahoma City Thunder           95               Utah Jazz
...         ...                    ...          ...                     ...
1055 2020-08-14         Denver Nuggets          109         Toronto Raptors
1056 2020-08-14             Miami Heat           92          Indiana Pacers
1057 2020-08-14  Oklahoma City Thunder          103    Los Angeles Clippers
1058 2020-08-14     Philadelphia 76ers          134         Houston Rockets
1059 2020-08-15      Memphis Grizzlies          122  Portland Trail Blazers

      HOME_PTS
0          130
1          112
2          100
3          124
4          100
...        ...
1055       117
1056       109
1057       107
1058        96
1059       126

[1060 rows x 5 columns]

In [7]:
from basketball_reference_scraper.shot_charts import get_shot_chart

s = get_shot_chart('2020-01-13', 'CHI', 'BOS')
print(s)

{'CHI':           x        y  QUARTER TIME_REMAINING              PLAYER MAKE_MISS  \
0   13.8 ft  26.7 ft        1        11:17.0     Lauri Markkanen      MISS
1   31.7 ft  17.6 ft        1        10:37.0    Tomáš Satoranský      MISS
2   32.0 ft  8.26 ft        1        10:06.0     Lauri Markkanen      MISS
3   24.0 ft  2.68 ft        1        10:05.0     Lauri Markkanen      MAKE
4   24.5 ft  4.97 ft        1         9:13.0      Daniel Gafford      MAKE
..      ...      ...      ...            ...                 ...       ...
76  25.3 ft  3.58 ft        4         3:35.0         Zach LaVine      MAKE
77  8.20 ft  27.8 ft        4         2:54.0         Zach LaVine      MAKE
78  17.7 ft  11.2 ft        4         1:47.0  Shaquille Harrison      MISS
79  17.2 ft  16.4 ft        4         0:54.0    Denzel Valentine      MAKE
80   6.1 ft  20.7 ft        4         0:18.0    Denzel Valentine      MAKE

    VALUE DISTANCE
0       3    26 ft
1       2    16 ft
2       2     9 ft
3       2     1 ft
4       2     2 ft
..    ...      ...
76      2     1 ft
77      3    29 ft
78      2    10 ft
79      2    15 ft
80      3    25 ft

[81 rows x 8 columns], 'BOS':           x        y  QUARTER TIME_REMAINING           PLAYER MAKE_MISS  \
0   25.9 ft  3.78 ft        1        11:35.0      Enes Kanter      MAKE
1    9.6 ft  9.55 ft        1        11:00.0     Jayson Tatum      MAKE
2   24.3 ft  4.77 ft        1         8:50.0      Enes Kanter      MAKE
3   22.5 ft  3.28 ft        1         8:19.0      Enes Kanter      MAKE
4   19.9 ft  8.16 ft        1         7:39.0     Jayson Tatum      MISS
..      ...      ...      ...            ...              ...       ...
78  25.3 ft  5.17 ft        4         3:03.0   Gordon Hayward      MAKE
79   6.7 ft  21.7 ft        4         2:39.0     Kemba Walker      MAKE
80  24.9 ft  29.1 ft        4         2:02.0     Kemba Walker      MAKE
81  34.1 ft  17.1 ft        4         1:33.0  Vincent Poirier      MISS
82  19.9 ft  5.17 ft        4         0:33.0  Vincent Poirier      MISS

    VALUE DISTANCE
0       2     2 ft
1       2    16 ft
2       2     2 ft
3       2     2 ft
4       2     6 ft
..    ...      ...
78      2     2 ft
79      3    25 ft
80      3    26 ft
81      2    17 ft
82      2     5 ft

[83 rows x 8 columns]}

In [8]:
from basketball_reference_scraper.injury_report import get_injury_report

s = get_injury_report()
print(s)

                PLAYER TEAM       DATE  \
0   Bogdan BogdanoviÄ‡  ATL 2021-02-05
1            Kris Dunn  ATL 2021-01-28
2      De'Andre Hunter  ATL 2021-02-07
3         Jaylen Brown  BOS 2021-02-07
4       Romeo Langford  BOS 2020-12-01
..                 ...  ...        ...
90         Mike Conley  UTA 2021-02-07
91       Elijah Hughes  UTA 2021-02-07
92        Juwan Morgan  UTA 2021-02-07
93       Thomas Bryant  WAS 2021-01-10
94   Russell Westbrook  WAS 2021-02-08

                                          DESCRIPTION          STATUS  \
0   The Hawks announced that Bogdanovic is making ...             Out
1   The Hawks announced that Dunn will miss at lea...             Out
2   The Hawks announced that Hunter will be re-eva...             Out
3   Brown did not play in Sunday's game (Feb. 7) a...      Day To Day
4   The Celtics announced G-F Romeo Langford under...             Out
..                                                ...             ...
90  Conley did not play in Sunday's game (Feb. 7) ...      Day To Day
91  Hughes did not play in Sunday's game (Feb. 7) ...      Day To Day
92  Morgan did not play in Sunday's (Feb. 7) game ...      Day To Day
93  Bryant tore the ACL in his left knee, accordin...  Out For Season
94  Westbrook is out for Monday's (Feb. 8) game ag...             Out

         INJURY
0          Knee
1   Right ankle
2    Right Knee
3          Knee
4   Right wrist
..          ...
90    Hamstring
91        Ankle
92      Illness
93    Left knee
94         Rest

[95 rows x 6 columns]

In [9]:
from basketball_reference_scraper.players import get_game_logs, get_player_headshot

df = get_game_logs('Pau Gasol', '2010-01-12', '2010-01-20', playoffs=False)
print(df)

url = get_player_headshot('Kobe Bryant')
print(url)

You searched for "Pau Gasol"
7 results found.
0: Pau Gasol
1: Marc Gasol
2: Paul Watson
3: Paul Davis
4: Paul Grant
5: Paul Long
6: Paul Silas
Pick one: 0
Results for Pau Gasol:

         DATE     AGE TEAM HOME/AWAY OPPONENT   RESULT GS     MP FG FGA  ...  \
40 2010-01-15  29-193  LAL      HOME      LAC  W (+40)  1  30:29  4  10  ...
42 2010-01-18  29-196  LAL      HOME      ORL   W (+6)  1  39:32  8  14  ...

   DRB TRB AST STL BLK TOV PF PTS GAME_SCORE  +/-
40   2   6   3   0   3   1  0  20       21.2  +22
42   7  10   2   1   0   1  4  17       14.4   +7

[2 rows x 28 columns]
You searched for "Kobe Bryant"
4 results found.
0: Kobe Bryant
1: Joe Bryant
2: Em Bryant
3: Mark Bryant
Pick one: 0
Results for Kobe Bryant:

https://d2cwpp38twqe55.cloudfront.net/req/202006192/images/players/bryanko01.jpg

In [10]:
team_to_abbreviation = {
    "ATLANTA HAWKS" : "ATL",
    "ST. LOUIS HAWKS" : "SLH",
    "MILWAUKEE HAWKS" : "MIL",
    "TRI-CITIES BLACKHAWKS" : "TCB",
    "BOSTON CELTICS" : "BOS",
    "BROOKLYN NETS" : "BRK",
    "NEW JERSEY NETS" : "NJN",
    "CHICAGO BULLS" : "CHI",
    "CHARLOTTE HORNETS": "CHH",
    "CHARLOTTE HORNETS": "CHO",
    "CHARLOTTE BOBCATS" : "CHA",
    "CLEVELAND CAVALIERS": "CLE",
    "DALLAS MAVERICKS" : "DAL",
    "DENVER NUGGETS" : "DEN",
    "DETROIT PISTONS" : "DET",
    "FORT WAYNE PISTONS" : "FWP",
    "GOLDEN STATE WARRIORS" : "GSW",
    "SAN FRANCISCO WARRIORS" : "SFW",
    "PHILADELPHIA WARRIORS" : "PHI",
    "HOUSTON ROCKETS" : "HOU",
    "INDIANA PACERS" : "IND",
    "LOS ANGELES CLIPPERS" : "LAC",
    "SAN DIEGO CLIPPERS" : "SDC",
    "BUFFALO BRAVES" : "BUF",
    "LOS ANGELES LAKERS" : "LAL",
    "MINNEAPOLIS LAKERS" : "MIN",
    "MEMPHIS GRIZZLIES" : "MEM",
    "VANCOUVER GRIZZLIES" : 'VAN',
    "MIAMI HEAT" : "MIA",
    "MILWAUKEE BUCKS" : "MIL",
    "MINNESOTA TIMBERWOLVES" : "MIN",
    "NEW ORLEANS PELICANS" : "NOP",
    "NEW ORLEANS HORNETS" : "NOK",
    "NEW ORLEANS HORNETS" : "NOH",
    "NEW YORK KNICKS" : "NYK",
    "OKLAHOMA CITY HORNETS" : "NOK",
    "OKLAHOMA CITY THUNDER" : "OKC",
    "SEATTLE SUPERSONICS" : "SEA",
    "ORLANDO MAGIC" : "ORL",
    "PHILADELPHIA 76ERS" : "PHI",
    "SYRACUSE NATIONALS" : "SYR",
    "PHOENIX SUNS" : "PHO",
    "PORTLAND TRAIL BLAZERS" : "POR",
    "SACRAMENTO KINGS" : "SAC",
    "KANSAS CITY KINGS" : "KCK",
    "KANSAS CITY-OMAHA KINGS" : "KCK",
    "CINCINNATI ROYALS" : "CIN",
    "ROCHESTER ROYALS" : "ROR",
    "SAN ANTONIO SPURS" : "SAS",
    "TORONTO RAPTORS" : "TOR",
    "UTAH JAZZ" : "UTA",
    "NEW ORLEANS JAZZ" : "NOJ",
    "WASHINGTON WIZARDS" : "WAS",
    "WASHINGTON BULLETS" : "WAS",
    "CAPITAL BULLETS" : "CAP",
    "BALTIMORE BULLETS" : "BAL",
    "CHICAGO ZEPHYRS" : "CHI",
    "CHICAGO PACKERS" : "CHI",
    "ANDERSON PACKERS" : "AND",
    "CHICAGO STAGS" : "CHI",
    "INDIANAPOLIS OLYMPIANS" : "IND",
    "SHEBOYGAN RED SKINS" : "SRS",
    "ST. LOUIS BOMBERS" : "SLB",
    "WASHINGTON CAPITOLS" : "WAS",
    "WATERLOO HAWKS" : "WAT"
}

In [11]:
# get a team's past 10 games from a given date:

#let's look at Golden State's 73-9 record from the 2015-2016 season
season_2016_df = get_schedule(2016, playoffs=False)

season_2016_df

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS
0,2015-10-27,Cleveland Cavaliers,95,Chicago Bulls,97
1,2015-10-27,Detroit Pistons,106,Atlanta Hawks,94
2,2015-10-27,New Orleans Pelicans,95,Golden State Warriors,111
3,2015-10-28,Washington Wizards,88,Orlando Magic,87
4,2015-10-28,Philadelphia 76ers,95,Boston Celtics,112
...,...,...,...,...,...
1225,2016-04-13,Atlanta Hawks,98,Washington Wizards,109
1226,2016-04-13,Memphis Grizzlies,104,Golden State Warriors,125
1227,2016-04-13,Utah Jazz,96,Los Angeles Lakers,101
1228,2016-04-13,Los Angeles Clippers,105,Phoenix Suns,114
1229,2016-04-13,Denver Nuggets,99,Portland Trail Blazers,107

In [12]:
#their largest loss was against the Blazers, on 2016-02-19, so we'll grab all the data of warrior games before this date
season_2016_pre_big_loss = season_2016_df.loc[(season_2016_df["DATE"] < "2016-02-19")]
#a line that didnt work: (team_to_abbreviation[str(season_2016_df["VISITOR"]).upper()] == "GSW" or team_to_abbreviation[str(season_2016_df["HOME"]).upper()] == "GSW")

# warriors_2016_pre_big_loss =  season_2016_pre_big_loss.loc[(team_to_abbreviation[season_2016_df["VISITOR"]] == "Golden State Warriors" | team_to_abbreviation[season_2016_df["HOME"]] == "Golden State Warriors")]

In [13]:
import pandas as pd
# warriors_2016_pre_big_loss = pd.DataFrame()

# for rows in season_2016_pre_big_loss:
#     if ((rows["HOME"] == "Golden State Warriors") or (rows ["VISITOR"] == "Golden State Warriors")):
#         warriors_2016_pre_big_loss.append(rows)
        
warriors_2016_home = season_2016_pre_big_loss.loc[(season_2016_df["HOME"] == "Golden State Warriors")]
warriors_2016_visitor = season_2016_pre_big_loss.loc[(season_2016_df["VISITOR"] == "Golden State Warriors")]

season = [warriors_2016_home, warriors_2016_visitor]

warriors_season = pd.concat(season)

warriors_season=  warriors_season.sort_values(by="DATE", ascending = False)

# warriors_season
last_10_games = pd.DataFrame(warriors_season[0:11])
last_10_games

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS
797,2016-02-10,Golden State Warriors,112,Phoenix Suns,104
786,2016-02-09,Houston Rockets,110,Golden State Warriors,123
766,2016-02-06,Oklahoma City Thunder,108,Golden State Warriors,116
738,2016-02-03,Golden State Warriors,134,Washington Wizards,121
716,2016-01-31,Golden State Warriors,116,New York Knicks,95
705,2016-01-30,Golden State Warriors,108,Philadelphia 76ers,105
689,2016-01-27,Dallas Mavericks,107,Golden State Warriors,127
673,2016-01-25,San Antonio Spurs,90,Golden State Warriors,120
651,2016-01-22,Indiana Pacers,110,Golden State Warriors,122
633,2016-01-20,Golden State Warriors,125,Chicago Bulls,94
621,2016-01-18,Golden State Warriors,132,Cleveland Cavaliers,98

In [14]:
last_10_games_stats = []
game_date = last_10_games.iloc[0]["DATE"]
date_no_time = str(game_date).split()[0]
date_no_time

visitor_team = team_to_abbreviation[last_10_games.iloc[0]["VISITOR"].upper()]
visitor_team

home_team = team_to_abbreviation[last_10_games.iloc[0]["HOME"].upper()]
home_team

team_box_score = get_box_scores(date_no_time, visitor_team, home_team, period='GAME', stat_type='BASIC')
team_box_score = pd.DataFrame(team_box_score["GSW"])

team_box_score.tail(1)


# for index, row in last_10_games.iterrows():
#     print("hi")

,PLAYER,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
13,Team Totals,240,37,89,.416,14,40,.350,24,29,...,8,42,50,24,12,7,13,22,112,NaN

In [17]:
def last10Games():
    team = input("Enter the full name of your team: ").title()
    abbreviation = team_to_abbreviation[team.upper()]
    print(f"team abbreviation for {team} is: {abbreviation}")
    
    date = input("Enter a date where you want to look at their stats the last 10 games (YYYY-MM-DD)")
    year = date.split("-")[0]
    print(f"looking up {str(int(year)-1)}-{year} season data before {date}")
    
    season_df = get_schedule(int(year), playoffs=False)
    
    season_before_date_df = season_df.loc[season_df["DATE"] < date] 
    
    team_home_df = season_before_date_df.loc[season_before_date_df["HOME"] == team]
    team_away_df = season_before_date_df.loc[season_before_date_df["VISITOR"] == team]
    
    team_season = [team_home_df, team_away_df]
    team_season_df = pd.concat(team_season).sort_values(by="DATE", ascending=False)
    
    if (len(team_season_df.index) < 10):
        last_10_games = pd.DataFrame(team_season_df[0:])
    else:
        last_10_games = pd.DataFrame(team_season_df[0:10])
        
    last_10_game_data = []
        
    for index, row in last_10_games.iterrows():
        game_date = row["DATE"]
        date_no_time = str(game_date).split()[0]
        
        visitor_team = team_to_abbreviation[row["VISITOR"].upper()]
        home_team = team_to_abbreviation[row["HOME"].upper()]
        
        print(f"getting info on game between: {home_team}(HOME) vs. {visitor_team}(AWAY) on {game_date}")
        
        team_box_score = get_box_scores(date_no_time, visitor_team, home_team, period='GAME', stat_type='BASIC')
        team_box_score = pd.DataFrame(team_box_score[abbreviation]).tail(1)
        
        last_10_game_data.append(team_box_score)
        
    last_10_game_stats = pd.concat(last_10_game_data)
    last_10_game_stats_df = pd.DataFrame(last_10_game_stats)
#     mean = pd.DataFrame(last_10_game_stats_df.mean())
    last_10_game_stats_df.reset_index()
    
    last_10_game_stats_df = last_10_game_stats_df[['FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']]
    
    last_10_game_stats_df["FG"] = last_10_game_stats_df["FG"].astype(int)
    last_10_game_stats_df["FGA"] = last_10_game_stats_df["FGA"].astype(int)
    last_10_game_stats_df["FG%"] = last_10_game_stats_df["FG%"].astype(float)
    last_10_game_stats_df["3P"] = last_10_game_stats_df["3P"].astype(int)
    last_10_game_stats_df["3PA"] = last_10_game_stats_df["3PA"].astype(int)
    last_10_game_stats_df["3P%"] = last_10_game_stats_df["3P%"].astype(float)
    last_10_game_stats_df["FT"] = last_10_game_stats_df["FT"].astype(int)
    last_10_game_stats_df["FTA"] = last_10_game_stats_df["FTA"].astype(int)
    last_10_game_stats_df["FT%"] = last_10_game_stats_df["FT%"].astype(float)
    last_10_game_stats_df["ORB"] = last_10_game_stats_df["ORB"].astype(int)
    last_10_game_stats_df["DRB"] = last_10_game_stats_df["DRB"].astype(int)
    last_10_game_stats_df["TRB"] = last_10_game_stats_df["TRB"].astype(int)
    last_10_game_stats_df["AST"] = last_10_game_stats_df["AST"].astype(int)
    last_10_game_stats_df["STL"] = last_10_game_stats_df["STL"].astype(int)
    last_10_game_stats_df["BLK"] = last_10_game_stats_df["BLK"].astype(int)
    last_10_game_stats_df["TOV"] = last_10_game_stats_df["TOV"].astype(int)
    last_10_game_stats_df["PF"] = last_10_game_stats_df["PF"].astype(int)
    last_10_game_stats_df["PTS"] = last_10_game_stats_df["PTS"].astype(int)

    return last_10_game_stats_df

In [20]:
mean = last10Games()
mean

Enter the full name of your team: Denver Nuggets
team abbreviation for Denver Nuggets is: DEN
Enter a date where you want to look at their stats the last 10 games (YYYY-MM-DD)2020-02-28
looking up 2019-2020 season data before 2020-02-28
getting info on game between: DEN(HOME) vs. DET(AWAY) on 2020-02-25 00:00:00
getting info on game between: DEN(HOME) vs. MIN(AWAY) on 2020-02-23 00:00:00
getting info on game between: OKC(HOME) vs. DEN(AWAY) on 2020-02-21 00:00:00
getting info on game between: DEN(HOME) vs. LAL(AWAY) on 2020-02-12 00:00:00
getting info on game between: DEN(HOME) vs. SAS(AWAY) on 2020-02-10 00:00:00
getting info on game between: PHO(HOME) vs. DEN(AWAY) on 2020-02-08 00:00:00
getting info on game between: UTA(HOME) vs. DEN(AWAY) on 2020-02-05 00:00:00
getting info on game between: DEN(HOME) vs. POR(AWAY) on 2020-02-04 00:00:00
getting info on game between: DET(HOME) vs. DEN(AWAY) on 2020-02-02 00:00:00
getting info on game between: MIL(HOME) vs. DEN(AWAY) on 2020-01-31 00:00:00

,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
13,44,76,0.579,9,19,0.474,18,22,0.818,9,32,41,33,12,3,18,20,115
13,53,90,0.589,11,30,0.367,11,17,0.647,5,33,38,29,9,7,13,24,128
13,37,77,0.481,6,27,0.222,21,23,0.913,8,31,39,19,7,3,19,20,101
12,44,88,0.500,11,25,0.440,17,22,0.773,3,39,42,32,9,2,10,26,116
13,45,80,0.563,18,35,0.514,19,23,0.826,9,28,37,34,7,5,10,16,127
13,45,82,0.549,11,28,0.393,16,21,0.762,8,32,40,23,7,7,14,22,117
12,39,90,0.433,7,30,0.233,13,18,0.722,13,39,52,23,8,5,11,17,98
13,46,90,0.511,17,34,0.500,18,25,0.720,12,38,50,30,5,7,13,22,127
12,48,96,0.500,10,32,0.313,17,22,0.773,14,33,47,30,7,7,9,19,123
12,48,100,0.480,22,46,0.478,9,9,1.000,7,43,50,29,8,10,12,19,127

In [21]:
mean.columns

Index(['FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [22]:
mean = mean[['FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']]
mean

,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
13,44,76,0.579,9,19,0.474,18,22,0.818,9,32,41,33,12,3,18,20,115
13,53,90,0.589,11,30,0.367,11,17,0.647,5,33,38,29,9,7,13,24,128
13,37,77,0.481,6,27,0.222,21,23,0.913,8,31,39,19,7,3,19,20,101
12,44,88,0.500,11,25,0.440,17,22,0.773,3,39,42,32,9,2,10,26,116
13,45,80,0.563,18,35,0.514,19,23,0.826,9,28,37,34,7,5,10,16,127
13,45,82,0.549,11,28,0.393,16,21,0.762,8,32,40,23,7,7,14,22,117
12,39,90,0.433,7,30,0.233,13,18,0.722,13,39,52,23,8,5,11,17,98
13,46,90,0.511,17,34,0.500,18,25,0.720,12,38,50,30,5,7,13,22,127
12,48,96,0.500,10,32,0.313,17,22,0.773,14,33,47,30,7,7,9,19,123
12,48,100,0.480,22,46,0.478,9,9,1.000,7,43,50,29,8,10,12,19,127

In [23]:
mean = mean.reset_index()
mean

,index,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,13,44,76,0.579,9,19,0.474,18,22,0.818,9,32,41,33,12,3,18,20,115
1,13,53,90,0.589,11,30,0.367,11,17,0.647,5,33,38,29,9,7,13,24,128
2,13,37,77,0.481,6,27,0.222,21,23,0.913,8,31,39,19,7,3,19,20,101
3,12,44,88,0.500,11,25,0.440,17,22,0.773,3,39,42,32,9,2,10,26,116
4,13,45,80,0.563,18,35,0.514,19,23,0.826,9,28,37,34,7,5,10,16,127
5,13,45,82,0.549,11,28,0.393,16,21,0.762,8,32,40,23,7,7,14,22,117
6,12,39,90,0.433,7,30,0.233,13,18,0.722,13,39,52,23,8,5,11,17,98
7,13,46,90,0.511,17,34,0.500,18,25,0.720,12,38,50,30,5,7,13,22,127
8,12,48,96,0.500,10,32,0.313,17,22,0.773,14,33,47,30,7,7,9,19,123
9,12,48,100,0.480,22,46,0.478,9,9,1.000,7,43,50,29,8,10,12,19,127

In [24]:
mean["FG"] = mean["FG"].astype(int)
mean["FGA"] = mean["FGA"].astype(int)
mean["FG%"] = mean["FG%"].astype(float)
mean["3P"] = mean["3P"].astype(int)
mean["3PA"] = mean["3PA"].astype(int)
mean["3P%"] = mean["3P%"].astype(float)
mean["FT"] = mean["FT"].astype(int)
mean["FTA"] = mean["FTA"].astype(int)
mean["FT%"] = mean["FT%"].astype(float)
mean["ORB"] = mean["ORB"].astype(int)
mean["DRB"] = mean["DRB"].astype(int)
mean["TRB"] = mean["TRB"].astype(int)
mean["AST"] = mean["AST"].astype(int)
mean["STL"] = mean["STL"].astype(int)
mean["BLK"] = mean["BLK"].astype(int)
mean["TOV"] = mean["TOV"].astype(int)
mean["PF"] = mean["PF"].astype(int)
mean["PTS"] = mean["PTS"].astype(int)

In [25]:
mean.dtypes

index      int64
FG         int64
FGA        int64
FG%      float64
3P         int64
3PA        int64
3P%      float64
FT         int64
FTA        int64
FT%      float64
ORB        int64
DRB        int64
TRB        int64
AST        int64
STL        int64
BLK        int64
TOV        int64
PF         int64
PTS        int64
dtype: object

In [26]:
mean.mean()

index     12.6000
FG        44.9000
FGA       86.9000
FG%        0.5185
3P        12.2000
3PA       30.6000
3P%        0.3934
FT        15.9000
FTA       20.2000
FT%        0.7954
ORB        8.8000
DRB       34.8000
TRB       43.6000
AST       28.2000
STL        7.9000
BLK        5.6000
TOV       12.9000
PF        20.5000
PTS      117.9000
dtype: float64

In [27]:
mean["ORB"].sum()

88

In [28]:
gsw = last10Games()

Enter the full name of your team: golden state warriors
team abbreviation for Golden State Warriors is: GSW
Enter a date where you want to look at their stats the last 10 games (YYYY-MM-DD)2020-02-01
looking up 2019-2020 season data before 2020-02-01
getting info on game between: BOS(HOME) vs. GSW(AWAY) on 2020-01-30 00:00:00
getting info on game between: PHI(HOME) vs. GSW(AWAY) on 2020-01-28 00:00:00
getting info on game between: GSW(HOME) vs. IND(AWAY) on 2020-01-24 00:00:00
getting info on game between: GSW(HOME) vs. UTA(AWAY) on 2020-01-22 00:00:00
getting info on game between: POR(HOME) vs. GSW(AWAY) on 2020-01-20 00:00:00
getting info on game between: GSW(HOME) vs. ORL(AWAY) on 2020-01-18 00:00:00
getting info on game between: GSW(HOME) vs. DEN(AWAY) on 2020-01-16 00:00:00
getting info on game between: GSW(HOME) vs. DAL(AWAY) on 2020-01-14 00:00:00
getting info on game between: MEM(HOME) vs. GSW(AWAY) on 2020-01-12 00:00:00
getting info on game between: LAC(HOME) vs. GSW(AWAY) on 2020-01-10 00:00:00

In [ ]:
por = last10Games()

In [29]:
gsw.mean()

FG      38.9000
FGA     91.4000
FG%      0.4266
3P      12.7000
3PA     36.7000
3P%      0.3411
FT      18.0000
FTA     22.1000
FT%      0.8178
ORB      9.5000
DRB     32.5000
TRB     42.0000
AST     27.3000
STL      8.0000
BLK      3.8000
TOV     14.0000
PF      19.6000
PTS    108.5000
dtype: float64

In [ ]:
por.mean()

In [30]:
gsw

,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
11,33,77,0.429,12,39,0.308,26,30,0.867,3,27,30,24,11,6,16,19,104
11,37,87,0.425,15,40,0.375,15,21,0.714,6,34,40,29,6,3,13,24,104
11,40,82,0.488,19,39,0.487,19,23,0.826,7,31,38,31,6,3,20,16,118
11,35,88,0.398,6,23,0.261,20,24,0.833,11,26,37,20,5,5,8,23,96
11,48,116,0.414,9,36,0.250,19,22,0.864,19,41,60,30,7,5,9,25,124
11,43,94,0.457,12,40,0.300,11,11,1.000,7,37,44,25,9,2,10,13,109
11,42,95,0.442,20,45,0.444,27,31,0.871,10,32,42,36,12,6,18,20,131
11,39,87,0.448,9,32,0.281,10,13,0.769,7,29,36,27,4,1,14,16,97
11,35,92,0.380,17,34,0.500,15,21,0.714,12,35,47,23,11,6,22,18,102
11,37,96,0.385,8,39,0.205,18,25,0.720,13,33,46,28,9,1,10,22,100

In [31]:
def seasonData():
    team = input("Enter the full name of your team: ").title()
    abbreviation = team_to_abbreviation[team.upper()]
    print(f"team abbreviation for {team} is: {abbreviation}")
    
    date = input("Enter a date where you want to look at their stats the last 10 games (YYYY-MM-DD)")
    year = input("Enter the end year of the season you want to look for: ")

    
    season_df = get_schedule(int(year), playoffs=False)
    
    season_before_date_df = season_df.loc[season_df["DATE"] < date] 
    
    team_home_df = season_before_date_df.loc[season_before_date_df["HOME"] == team]
    team_away_df = season_before_date_df.loc[season_before_date_df["VISITOR"] == team]
    
    team_season = [team_home_df, team_away_df]
    team_season_df = pd.concat(team_season).sort_values(by="DATE", ascending=False)
        
    season_data = []
    win_loss = []
        
    for index, row in pd.DataFrame(team_season_df).iterrows():
        game_date = row["DATE"]
        date_no_time = str(game_date).split()[0]
        
        visitor_team = team_to_abbreviation[row["VISITOR"].upper()]
        home_team = team_to_abbreviation[row["HOME"].upper()]
        
        if int(row["HOME_PTS"]) > int(row["VISITOR_PTS"]):
            home_result = "W"
            away_result = "L"
        else:
            home_result = "L"
            away_result = "W"
            
        team_result = (home_result if home_team == abbreviation else away_result)
        
        print(f"getting info on game between: {home_team}(HOME){home_result} vs. {visitor_team}(AWAY){away_result} on {game_date}")
        
        team_box_score = get_box_scores(date_no_time, visitor_team, home_team, period='GAME', stat_type='BASIC')
        team_box_score = pd.DataFrame(team_box_score[abbreviation]).tail(1)
        
        season_data.append(team_box_score)
        win_loss.append(team_result)
        
    season_stats = pd.concat(season_data)
    season_stats_df = pd.DataFrame(season_stats)
#     mean = pd.DataFrame(last_10_game_stats_df.mean())
    season_stats_df.reset_index()
    
    season_stats_df = season_stats_df[['FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']]
    
    season_stats_df["FG"] = season_stats_df["FG"].astype(int)
    season_stats_df["FGA"] = season_stats_df["FGA"].astype(int)
    season_stats_df["FG%"] = season_stats_df["FG%"].astype(float)
    season_stats_df["3P"] = season_stats_df["3P"].astype(int)
    season_stats_df["3PA"] = season_stats_df["3PA"].astype(int)
    season_stats_df["3P%"] = season_stats_df["3P%"].astype(float)
    season_stats_df["FT"] = season_stats_df["FT"].astype(int)
    season_stats_df["FTA"] = season_stats_df["FTA"].astype(int)
    season_stats_df["FT%"] = season_stats_df["FT%"].astype(float)
    season_stats_df["ORB"] = season_stats_df["ORB"].astype(int)
    season_stats_df["DRB"] = season_stats_df["DRB"].astype(int)
    season_stats_df["TRB"] = season_stats_df["TRB"].astype(int)
    season_stats_df["AST"] = season_stats_df["AST"].astype(int)
    season_stats_df["STL"] = season_stats_df["STL"].astype(int)
    season_stats_df["BLK"] = season_stats_df["BLK"].astype(int)
    season_stats_df["TOV"] = season_stats_df["TOV"].astype(int)
    season_stats_df["PF"] = season_stats_df["PF"].astype(int)
    season_stats_df["PTS"] = season_stats_df["PTS"].astype(int)
    
    print(str(win_loss))

    return season_stats_df

# ANALYZING THE 73-9 2015-2016 WARRIORS

In [32]:
gsw_szn = seasonData()

Enter the full name of your team: golden state warriors
team abbreviation for Golden State Warriors is: GSW
Enter a date where you want to look at their stats the last 10 games (YYYY-MM-DD)2013-02-02
Enter the end year of the season you want to look for: 2013
getting info on game between: GSW(HOME)W vs. DAL(AWAY)L on 2013-01-31 00:00:00
getting info on game between: CLE(HOME)L vs. GSW(AWAY)W on 2013-01-29 00:00:00
getting info on game between: TOR(HOME)L vs. GSW(AWAY)W on 2013-01-28 00:00:00
getting info on game between: MIL(HOME)W vs. GSW(AWAY)L on 2013-01-26 00:00:00
getting info on game between: CHI(HOME)W vs. GSW(AWAY)L on 2013-01-25 00:00:00
getting info on game between: GSW(HOME)W vs. OKC(AWAY)L on 2013-01-23 00:00:00
getting info on game between: GSW(HOME)W vs. LAC(AWAY)L on 2013-01-21 00:00:00
getting info on game between: NOH(HOME)L vs. GSW(AWAY)W on 2013-01-19 00:00:00
getting info on game between: SAS(HOME)W vs. GSW(AWAY)L on 2013-01-18 00:00:00
getting info on game between: GSW(HOME)L vs. MIA(AWAY)W on 2013-01-16 00:00:00
getting info on game between: DEN(HOME)W vs. GSW(AWAY)L on 2013-01-13 00:00:00
getting info on game between: GSW(HOME)W vs. POR(AWAY)L on 2013-01-11 00:00:00
getting info on game between: GSW(HOME)L vs. MEM(AWAY)W on 2013-01-09 00:00:00
getting info on game between: LAC(HOME)W vs. GSW(AWAY)L on 2013-01-05 00:00:00
getting info on game between: GSW(HOME)W vs. LAC(AWAY)L on 2013-01-02 00:00:00
getting info on game between: GSW(HOME)W vs. BOS(AWAY)L on 2012-12-29 00:00:00
getting info on game between: GSW(HOME)W vs. PHI(AWAY)L on 2012-12-28 00:00:00
getting info on game between: UTA(HOME)L vs. GSW(AWAY)W on 2012-12-26 00:00:00
getting info on game between: GSW(HOME)L vs. LAL(AWAY)W on 2012-12-22 00:00:00
getting info on game between: GSW(HOME)W vs. CHA(AWAY)L on 2012-12-21 00:00:00
getting info on game between: SAC(HOME)W vs. GSW(AWAY)L on 2012-12-19 00:00:00
getting info on game between: GSW(HOME)W vs. NOH(AWAY)L on 2012-12-18 00:00:00
getting info on game between: ATL(HOME)L vs. GSW(AWAY)W on 2012-12-15 00:00:00
getting info on game between: ORL(HOME)W vs. GSW(AWAY)L on 2012-12-14 00:00:00
getting info on game between: MIA(HOME)L vs. GSW(AWAY)W on 2012-12-12 00:00:00
getting info on game between: CHA(HOME)L vs. GSW(AWAY)W on 2012-12-10 00:00:00
getting info on game between: WAS(HOME)L vs. GSW(AWAY)W on 2012-12-08 00:00:00
getting info on game between: BRK(HOME)L vs. GSW(AWAY)W on 2012-12-07 00:00:00
getting info on game between: DET(HOME)L vs. GSW(AWAY)W on 2012-12-05 00:00:00
getting info on game between: GSW(HOME)L vs. ORL(AWAY)W on 2012-12-03 00:00:00
getting info on game between: GSW(HOME)W vs. IND(AWAY)L on 2012-12-01 00:00:00
getting info on game between: GSW(HOME)W vs. DEN(AWAY)L on 2012-11-29 00:00:00
getting info on game between: GSW(HOME)W vs. MIN(AWAY)L on 2012-11-24 00:00:00
getting info on game between: DEN(HOME)W vs. GSW(AWAY)L on 2012-11-23 00:00:00
getting info on game between: GSW(HOME)W vs. BRK(AWAY)L on 2012-11-21 00:00:00
getting info on game between: DAL(HOME)L vs. GSW(AWAY)W on 2012-11-19 00:00:00
getting info on game between: OKC(HOME)W vs. GSW(AWAY)L on 2012-11-18 00:00:00
getting info on game between: MIN(HOME)L vs. GSW(AWAY)W on 2012-11-16 00:00:00
getting info on game between: GSW(HOME)W vs. ATL(AWAY)L on 2012-11-14 00:00:00
getting info on game between: GSW(HOME)L vs. DEN(AWAY)W on 2012-11-10 00:00:00
getting info on game between: LAL(HOME)W vs. GSW(AWAY)L on 2012-11-09 00:00:00
getting info on game between: GSW(HOME)W vs. CLE(AWAY)L on 2012-11-07 00:00:00
getting info on game between: SAC(HOME)W vs. GSW(AWAY)L on 2012-11-05 00:00:00
getting info on game between: LAC(HOME)L vs. GSW(AWAY)W on 2012-11-03 00:00:00
getting info on game between: GSW(HOME)L vs. MEM(AWAY)W on 2012-11-02 00:00:00
getting info on game between: PHO(HOME)L vs. GSW(AWAY)W on 2012-10-31 00:00:00
['W', 'W', 'W', 'L', 'L', 'W', 'W', 'W', 'L', 'L', 'L', 'W', 'L', 'L', 'W', 'W', 'W', 'W', 'L', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'L', 'L', 'W', 'L', 'W', 'L', 'W']

In [33]:
gsw_szn

,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
13,36,84,0.429,7,20,0.350,21,25,0.840,12,34,46,26,6,4,12,21,100
13,45,84,0.536,11,16,0.688,7,10,0.700,7,32,39,31,8,9,14,23,108
13,46,86,0.535,6,15,0.400,16,20,0.800,13,36,49,22,4,8,13,19,114
13,39,93,0.419,13,28,0.464,11,11,1.000,12,38,50,25,8,4,15,25,102
13,27,78,0.346,4,19,0.211,29,33,0.879,10,27,37,12,6,5,11,19,87
13,37,84,0.440,6,23,0.261,24,27,0.889,11,29,40,20,10,3,15,21,104
13,39,75,0.520,12,22,0.545,16,18,0.889,6,33,39,25,4,2,17,21,106
13,38,77,0.494,10,22,0.455,30,35,0.857,10,23,33,25,10,1,14,19,116
13,36,84,0.429,4,16,0.250,12,14,0.857,7,35,42,23,4,2,9,21,88
13,29,80,0.363,3,12,0.250,14,18,0.778,11,41,52,17,5,2,21,21,75
13,43,83,0.518,13,24,0.542,6,8,0.750,6,33,39,28,3,5,18,24,105
13,41,86,0.477,6,15,0.400,15,18,0.833,8,39,47,28,10,5,11,16,103
13,33,71,0.465,7,17,0.412,14,20,0.700,6,32,38,23,8,2,15,21,87
13,32,72,0.444,5,20,0.250,20,26,0.769,5,25,30,19,4,8,16,17,89
13,42,84,0.500,12,23,0.522,19,22,0.864,13,40,53,29,11,4,20,27,115
13,38,73,0.521,12,19,0.632,13,16,0.813,5,41,46,21,8,10,18,22,101
13,34,80,0.425,7,17,0.412,21,26,0.808,9,43,52,20,5,3,18,19,96
13,33,82,0.402,9,18,0.500,19,20,0.950,9,34,43,19,10,6,10,18,94
13,46,103,0.447,10,29,0.345,13,15,0.867,15,32,47,26,13,5,19,22,115
13,44,85,0.518,14,27,0.519,13,16,0.813,12,36,48,31,4,9,11,24,115
13,46,92,0.500,13,26,0.500,22,25,0.880,14,28,42,21,4,6,12,27,127
13,34,78,0.436,6,18,0.333,29,34,0.853,16,28,44,25,8,2,14,15,103
13,49,99,0.495,10,24,0.417,7,8,0.875,10,44,54,32,10,3,11,25,115
13,34,92,0.370,7,20,0.350,10,11,0.909,16,33,49,19,5,2,12,15,85
13,38,82,0.463,9,24,0.375,12,14,0.857,8,33,41,20,9,2,13,14,97
13,38,84,0.452,8,20,0.400,20,23,0.870,14,32,46,28,9,4,16,26,104
13,35,81,0.432,9,22,0.409,22,27,0.815,13,44,57,22,4,5,19,16,101
13,46,90,0.511,9,19,0.474,8,10,0.800,15,32,47,24,9,1,11,21,109
13,34,75,0.453,9,24,0.375,27,34,0.794,9,26,35,24,9,7,10,22,104
13,37,81,0.457,7,17,0.412,13,18,0.722,9,34,43,23,5,5,13,20,94
13,38,80,0.475,9,20,0.450,18,19,0.947,11,30,41,22,5,3,17,22,103
13,44,86,0.512,8,18,0.444,10,13,0.769,9,34,43,29,10,5,16,22,106
13,33,78,0.423,6,21,0.286,24,29,0.828,13,35,48,18,1,3,13,25,96
13,35,80,0.438,7,17,0.412,14,18,0.778,8,37,45,22,8,5,14,30,91
13,40,75,0.533,7,15,0.467,15,19,0.789,12,31,43,24,3,1,15,17,102
13,37,91,0.407,9,24,0.375,22,30,0.733,19,43,62,19,10,2,20,24,105
13,43,82,0.524,5,16,0.313,18,22,0.818,8,27,35,23,8,4,13,18,109
13,43,85,0.506,2,15,0.133,18,26,0.692,17,33,50,21,3,5,15,26,106
13,33,71,0.465,5,18,0.278,21,25,0.840,10,34,44,23,7,1,23,22,92
13,39,102,0.382,9,25,0.360,14,23,0.609,13,41,54,23,11,5,14,26,101
13,29,86,0.337,7,25,0.280,12,20,0.600,13,34,47,12,5,3,18,25,77
13,42,78,0.538,5,18,0.278,17,23,0.739,7,37,44,28,11,4,16,22,106
13,31,78,0.397,6,21,0.286,24,28,0.857,7,31,38,21,5,2,13,17,92
13,41,84,0.488,4,16,0.250,28,39,0.718,16,32,48,22,7,2,13,34,114
13,36,80,0.450,10,20,0.500,12,17,0.706,9,27,36,21,5,5,18,24,94
13,33,86,0.384,5,17,0.294,16,23,0.696,17,32,49,19,9,3,18,20,87

In [34]:
gsw_szn.mean()

FG      37.956522
FGA     83.043478
FG%      0.457739
3P       7.869565
3PA     20.043478
3P%      0.388239
FT      17.086957
FTA     21.217391
FT%      0.807609
ORB     10.869565
DRB     33.804348
TRB     44.673913
AST     22.934783
STL      6.978261
BLK      4.065217
TOV     14.869565
PF      21.630435
PTS    100.869565
dtype: float64

# AI Portion

In [35]:
# X = voice.drop("label", axis=1)
# y = voice["label"].values.reshape(-1,1)
# print(X.shape, y.shape)
import numpy

X = gsw_szn
y=numpy.array(['W', 'W', 'W', 'L', 'L', 'W', 'W', 'W', 'L', 'L', 'L', 'W', 'L', 'L', 'W', 'W', 'W', 'W', 'L', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'L', 'L', 'W', 'L', 'W', 'L', 'W']).reshape(-1,1)

print(X.shape, y.shape)

(46, 18) (46, 1)

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [37]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression()

In [38]:
classifier.fit(X_train, y_train)

/Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [39]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.9166666666666666

In [40]:
predictions = classifier.predict(X_test)
print(f"Season Predictions:   {predictions[:]}")
print(f"Actual labels: {y_test[:10].tolist()}")

Season Predictions:   ['W' 'L' 'W' 'W' 'L' 'W' 'L' 'W' 'L' 'W' 'W' 'W']
Actual labels: [['W'], ['L'], ['W'], ['W'], ['L'], ['W'], ['L'], ['W'], ['W'], ['W']]

# looking at the denver nuggets team that came back from 3-1 deficits last year consecutively

In [ ]:
denver_szn = seasonData()

In [ ]:
denver_szn

In [ ]:
import numpy

X = denver_szn
y=numpy.array(['W', 'W', 'L', 'L', 'W', 'W', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'L', 'W', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'L', 'L', 'L', 'W', 'L', 'L', 'W', 'W', 'W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'L', 'L', 'W', 'W', 'W']).reshape(-1,1)
print(X.shape, y.shape)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [ ]:
classifier.fit(X_train, y_train)

In [ ]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

In [ ]:
predictions = classifier.predict(X_test)
print(f"Season Predictions:   {predictions[:]}")
print(f"Actual labels: {y_test[:10].tolist()}")

In [42]:
philly_szn = seasonData()

Enter the full name of your team: sacramento kings
team abbreviation for Sacramento Kings is: SAC
Enter a date where you want to look at their stats the last 10 games (YYYY-MM-DD)2020-03-05
Enter the end year of the season you want to look for: 2020
getting info on game between: SAC(HOME)W vs. WAS(AWAY)L on 2020-03-03 00:00:00
getting info on game between: SAC(HOME)W vs. DET(AWAY)L on 2020-03-01 00:00:00
getting info on game between: MEM(HOME)L vs. SAC(AWAY)W on 2020-02-28 00:00:00
getting info on game between: OKC(HOME)W vs. SAC(AWAY)L on 2020-02-27 00:00:00
getting info on game between: GSW(HOME)L vs. SAC(AWAY)W on 2020-02-25 00:00:00
getting info on game between: LAC(HOME)L vs. SAC(AWAY)W on 2020-02-22 00:00:00
getting info on game between: SAC(HOME)W vs. MEM(AWAY)L on 2020-02-20 00:00:00
getting info on game between: DAL(HOME)W vs. SAC(AWAY)L on 2020-02-12 00:00:00
getting info on game between: MIL(HOME)W vs. SAC(AWAY)L on 2020-02-10 00:00:00
getting info on game between: SAC(HOME)W vs. SAS(AWAY)L on 2020-02-08 00:00:00
getting info on game between: SAC(HOME)W vs. MIA(AWAY)L on 2020-02-07 00:00:00
getting info on game between: SAC(HOME)W vs. MIN(AWAY)L on 2020-02-03 00:00:00
getting info on game between: SAC(HOME)L vs. LAL(AWAY)W on 2020-02-01 00:00:00
getting info on game between: LAC(HOME)L vs. SAC(AWAY)W on 2020-01-30 00:00:00
getting info on game between: SAC(HOME)L vs. OKC(AWAY)W on 2020-01-29 00:00:00
getting info on game between: MIN(HOME)L vs. SAC(AWAY)W on 2020-01-27 00:00:00
getting info on game between: CHI(HOME)L vs. SAC(AWAY)W on 2020-01-24 00:00:00
getting info on game between: DET(HOME)W vs. SAC(AWAY)L on 2020-01-22 00:00:00
getting info on game between: MIA(HOME)W vs. SAC(AWAY)L on 2020-01-20 00:00:00
getting info on game between: UTA(HOME)W vs. SAC(AWAY)L on 2020-01-18 00:00:00
getting info on game between: SAC(HOME)L vs. DAL(AWAY)W on 2020-01-15 00:00:00
getting info on game between: SAC(HOME)L vs. ORL(AWAY)W on 2020-01-13 00:00:00
getting info on game between: SAC(HOME)L vs. MIL(AWAY)W on 2020-01-10 00:00:00
getting info on game between: PHO(HOME)L vs. SAC(AWAY)W on 2020-01-07 00:00:00
getting info on game between: SAC(HOME)W vs. GSW(AWAY)L on 2020-01-06 00:00:00
getting info on game between: SAC(HOME)L vs. NOP(AWAY)W on 2020-01-04 00:00:00
getting info on game between: SAC(HOME)W vs. MEM(AWAY)L on 2020-01-02 00:00:00
getting info on game between: SAC(HOME)L vs. LAC(AWAY)W on 2019-12-31 00:00:00
getting info on game between: DEN(HOME)W vs. SAC(AWAY)L on 2019-12-29 00:00:00
getting info on game between: SAC(HOME)L vs. PHO(AWAY)W on 2019-12-28 00:00:00
getting info on game between: SAC(HOME)L vs. MIN(AWAY)W on 2019-12-26 00:00:00
getting info on game between: SAC(HOME)L vs. HOU(AWAY)W on 2019-12-23 00:00:00
getting info on game between: MEM(HOME)W vs. SAC(AWAY)L on 2019-12-21 00:00:00
getting info on game between: IND(HOME)W vs. SAC(AWAY)L on 2019-12-20 00:00:00
getting info on game between: CHO(HOME)W vs. SAC(AWAY)L on 2019-12-17 00:00:00
getting info on game between: GSW(HOME)L vs. SAC(AWAY)W on 2019-12-15 00:00:00
getting info on game between: SAC(HOME)L vs. NYK(AWAY)W on 2019-12-13 00:00:00
getting info on game between: SAC(HOME)W vs. OKC(AWAY)L on 2019-12-11 00:00:00
getting info on game between: HOU(HOME)L vs. SAC(AWAY)W on 2019-12-09 00:00:00
getting info on game between: DAL(HOME)L vs. SAC(AWAY)W on 2019-12-08 00:00:00
getting info on game between: SAS(HOME)W vs. SAC(AWAY)L on 2019-12-06 00:00:00
getting info on game between: POR(HOME)W vs. SAC(AWAY)L on 2019-12-04 00:00:00
getting info on game between: SAC(HOME)L vs. CHI(AWAY)W on 2019-12-02 00:00:00
getting info on game between: SAC(HOME)W vs. DEN(AWAY)L on 2019-11-30 00:00:00
getting info on game between: PHI(HOME)W vs. SAC(AWAY)L on 2019-11-27 00:00:00
getting info on game between: BOS(HOME)W vs. SAC(AWAY)L on 2019-11-25 00:00:00
getting info on game between: WAS(HOME)L vs. SAC(AWAY)W on 2019-11-24 00:00:00
getting info on game between: BRK(HOME)W vs. SAC(AWAY)L on 2019-11-22 00:00:00
getting info on game between: SAC(HOME)W vs. PHO(AWAY)L on 2019-11-19 00:00:00
getting info on game between: SAC(HOME)W vs. BOS(AWAY)L on 2019-11-17 00:00:00
getting info on game between: LAL(HOME)W vs. SAC(AWAY)L on 2019-11-15 00:00:00
getting info on game between: SAC(HOME)W vs. POR(AWAY)L on 2019-11-12 00:00:00
getting info on game between: ATL(HOME)L vs. SAC(AWAY)W on 2019-11-08 00:00:00
getting info on game between: TOR(HOME)W vs. SAC(AWAY)L on 2019-11-06 00:00:00
getting info on game between: NYK(HOME)L vs. SAC(AWAY)W on 2019-11-03 00:00:00
getting info on game between: SAC(HOME)W vs. UTA(AWAY)L on 2019-11-01 00:00:00
getting info on game between: SAC(HOME)L vs. CHO(AWAY)W on 2019-10-30 00:00:00
getting info on game between: SAC(HOME)L vs. DEN(AWAY)W on 2019-10-28 00:00:00
getting info on game between: UTA(HOME)W vs. SAC(AWAY)L on 2019-10-26 00:00:00
getting info on game between: SAC(HOME)L vs. POR(AWAY)W on 2019-10-25 00:00:00
getting info on game between: PHO(HOME)W vs. SAC(AWAY)L on 2019-10-23 00:00:00
['W', 'W', 'W', 'L', 'W', 'W', 'W', 'L', 'L', 'W', 'W', 'W', 'L', 'W', 'L', 'W', 'W', 'L', 'L', 'L', 'L', 'L', 'L', 'W', 'W', 'L', 'W', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'W', 'L', 'W', 'W', 'W', 'L', 'L', 'L', 'W', 'L', 'L', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'L', 'L', 'L', 'L', 'L']

In [52]:
philly_szn

,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
12,50,89,0.562,13,29,0.448,20,24,0.833,8,34,42,23,13,2,15,24,133
13,37,91,0.407,9,35,0.257,23,26,0.885,17,34,51,18,8,7,10,20,106
13,38,91,0.418,11,38,0.289,17,21,0.810,8,39,47,24,11,3,9,16,104
12,41,91,0.451,12,35,0.343,14,14,1.000,12,33,45,30,6,2,15,33,108
13,40,76,0.526,13,30,0.433,19,34,0.559,2,38,40,25,7,4,10,23,112
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,44,96,0.458,14,46,0.304,9,12,0.750,10,29,39,26,11,5,15,19,111
13,36,91,0.396,12,37,0.324,10,16,0.625,15,33,48,25,6,8,12,21,94
13,30,81,0.370,7,26,0.269,14,17,0.824,6,25,31,16,5,3,17,19,81
13,37,87,0.425,15,37,0.405,23,27,0.852,13,30,43,17,10,2,17,26,112
13,34,87,0.391,10,29,0.345,17,26,0.654,12,35,47,17,5,5,26,24,95

In [53]:
X = philly_szn
y=numpy.array(['W', 'W', 'W', 'L', 'W', 'W', 'W', 'L', 'L', 'W', 'W', 'W', 'L', 'W', 'L', 'W', 'W', 'L', 'L', 'L', 'L', 'L', 'L', 'W', 'W', 'L', 'W', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'W', 'L', 'W', 'W', 'W', 'L', 'L', 'L', 'W', 'L', 'L', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'L', 'L', 'L', 'L', 'L']).reshape(-1,1)

print(X.shape, y.shape)

(61, 18) (61, 1)

In [60]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1,test_size=0.5)

In [61]:
classifier.fit(X_train, y_train)

/Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [62]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.8064516129032258

In [65]:
predictions = classifier.predict(X_test)
print(f"Season Predictions:   {predictions}")
print(f"Actual labels: {y_test[:len(predictions)//2].tolist()}")

Season Predictions:   ['L' 'W' 'W' 'W' 'W' 'W' 'W' 'L' 'L' 'W' 'W' 'W' 'W' 'L' 'L' 'W' 'W' 'W'
 'W' 'L' 'L' 'L' 'L' 'W' 'L' 'L' 'L' 'W' 'W' 'W' 'W']
Actual labels: [['L'], ['L'], ['W'], ['W'], ['W'], ['W'], ['L'], ['L'], ['L'], ['W'], ['W'], ['W'], ['W'], ['L'], ['L']]

In [68]:
y_test = y_test.flatten()

y_test

array(['L', 'L', 'W', 'W', 'W', 'W', 'L', 'L', 'L', 'W', 'W', 'W', 'W',
       'L', 'L', 'L', 'L', 'W', 'L', 'L', 'L', 'L', 'L', 'W', 'L', 'L',
       'L', 'W', 'W', 'L', 'W'], dtype='<U1')

In [69]:
from sklearn.metrics import accuracy_score

accuracy_score(predictions, y_test)

0.8064516129032258